### ISSUE TITLE
支持低频存储

### ISSUE THREAD

**Issue by t1anz0ng** [qiniu/qshell#101]
将文件修改为低频存储 API：
https://developer.qiniu.com/kodo/api/3710/modify-the-file-type

stat 接口增加了低频存储的返回字段 type
https://developer.qiniu.com/kodo/api/1308/stat

上传策略增加字段 fileType
http://developer.qiniu.com/kodo/manual/1206/put-policy

type 为 0 表示正常存储，1 为低频存储

**Comment by jemygraw** [comment]
rput，fput，stat，qupload，qupload2

**Comment by jemygraw** [comment]
fixed in new version 2.0.8
