### ISSUE TITLE
qshell的alilistbucket参数没有添加Signature的字段

### ISSUE THREAD

**Issue by gaosy87** [qiniu/qshell#105]
执行：qshell alilistbucket vodpub.oss-cn-hangzhou.aliyuncs.com vodpub ${AccessKeyId} ${AccessKeySecret} oss_file_list.txt
错误日志：<Error> <Code>SignatureDoesNotMatch</Code> <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message> <RequestId>594B3259CE2B80FC00745EE0</RequestId> <HostId>wepub.oss-cn-hangzhou.aliyuncs.com</HostId> <OSSAccessKeyId>LTAI0oLb06NMaeCV</OSSAccessKeyId> <SignatureProvided>mc07hDVYQzFTSumXyb6esyRsLms=</SignatureProvided> <StringToSign>GET
如果：阿里云OSS接口已经更新，在url添加了Signature的字段，而qshell没有添入这个字段。

**Comment by jemygraw** [comment]
Fixed in 2.0.9
