### ISSUE TITLE
请问一下我根据链接下载2.0.9为什么无法解压

### ISSUE THREAD

**Issue by hct7511** [qiniu/qshell#111]
有跟我遇到同样问题的小伙伴么，
wget http://devtools.qiniu.com/2.0.9/qshell-linux-x64 后，不是压缩类型的文件。
小白求指教.

**Comment by jemygraw** [comment]
这个不是压缩文件，直接 chmod +x qshell-linux-x64 就可以使用 ./qshell-linux-x64 运行了。
