### ISSUE TITLE
请教下怎么绑定一个C的符号到qshell里面？

### ISSUE THREAD

**Issue by gpmn** [qiniu/qshell#114]
我想基于qshell在搞一个小工具，嵌入c代码中，能够从qshell去操作C的代码和函数。

函数已经搞定了，但是C的变量想不到好办法。

set(var,1000)之类的做法倒是可以搞定，但是使用的时候实在不方便。希望能做来和go和qshell内的变量一样操作。

求牛牛牛牛牛牛牛的兄弟们指导下！！！！

**Comment by gpmn** [comment]
不好意思，得到qlang去求助，囧

**Comment by jemygraw** [comment]
嘿嘿
