### ISSUE TITLE
【安全性加强】拒绝读取所有人可读的秘钥文件

### ISSUE THREAD

**Issue by zinsserzh** [qiniu/qshell#118]
https://github.com/qiniu/qshell/pull/117
之前PR的跟进
很多常见的linux程序(例如ssh)在读取秘钥文件的时候会检查文件mode(通过os.Stat)，如果文件是所有人可读的会拒绝请求并报错退出。这个是设计问题了，我不知道有没有任何设计期望的正常使用情况下需要所有人可读，我也不知道go语言os.Stat跨平台的行为是什么。如果正常使用情况不需要秘钥文件所有人可读，我强烈建议增加这个检查，但是我对这个项目code base不是很了解，也没有跨平台测试的环境，希望repo维护者能处理这个事情

**Comment by jemygraw** [comment]
之前限制文件的rw属性的pr已经处理了，读取文件的时候再检查rw属性这个会考虑。

**Comment by zinsserzh** [comment]
会考虑为什么close issue

**Comment by jemygraw** [comment]
这个问题暂时不处理，如果文件创建的时候就是用户可读写的话，不考虑该文件被拷贝到其他地方的情况，对于安全性很高的场合，建议用完即删除account信息。
account信息目前在命令运行时会打印出具体路径，供用户查看。
