### ISSUE TITLE
Error stat local file

### ISSUE THREAD

**Issue by wang-fu** [qiniu/qshell#124]
2017/08/31 18:28:18 [INFO][qshell] qupload.go:232 Use the last cached local sync dir file list ...
2017/08/31 18:28:18 [ERROR][qshell] qupload.go:440: Error stat local file /Users/app...

上传了一个文件，后来在网页上操作了删除。
在本地文件也手动删除
再去通过qshell qupload2 \
	--thread-count=10 \
	--src-dir=/User/xx/x/xx/xx/xx/upload \
	--access-key=xxx\
	--secret-key=xxx \
	--bucket=xxx

上传的时候会报这个错误。
不过最后直接把目录名改了下，在上传就好了。
是因为去qshell上传使用了文件缓存的吗？这块不是很清楚。 有人帮忙解答下吗，谢谢

**Comment by jemygraw** [comment]
你指定下 --rescan-local 选项就可以了，因为qshell为了实现大目录的同步，会对目录进行缓存，如果下一次运行时不指定 --rescan-local  选项，那么会使用上一次获取成功的目录列表，这样的话，你本地文件删除后，再去根据旧的列表上传，就会出现找不到这个文件的错误，就是`Error stat local file xxxx`

**Comment by wang-fu** [comment]
好的，谢谢，是这个原因。--rescan-local 这个参数可以加在文档https://github.com/qiniu/qshell/blob/master/docs/qupload.md
中吗，这样遇到问题比较容易找到方向。

**Comment by jemygraw** [comment]
直接用`qshell qupload2 -h` 就可以看到。因为不是所有用户都需要从命令行指定参数，所以没有写在文档里面，只有必要的时候才告知该命令。
