### ISSUE TITLE
在ubuntu下使用qshell qupload命令时上传到七牛空间的文件名没有加上相对路径

### ISSUE THREAD

**Issue by zjh129** [qiniu/qshell#126]
64位和32位都是这样的情况，这是我的配置文件
{
   "src_dir"            :   "/data/asset",
   "bucket"             :   "asset",
   "overwrite"          :   true,
   "ignore_dir"         :   true,
   "skip_file_prefixes" :   "test,demo,",
   "skip_path_prefixes" :   "hello/,temp/",
   "skip_fixed_strings" :   ".svn,.git,.bowerrc,upload.conf,bower.json",
   "skip_suffixes"      :   ".DS_Store,.exe",
   "rescan_local"       :   true
}

**Comment by jemygraw** [comment]
因为你配置了
```
"ignore_dir" : true,
```
 这个默认是false，你设置为true表示忽略相对路径了，看文档。
