### ISSUE TITLE
无法下载文件到本地 The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by xiaobo** [qiniu/qshell#127]
1. 使用https://dn-devtools.qbox.me/2.1.3/qshell-windows-x64.exe （已经重命名为qshell.exe)
2. 在本地执行 qshell qdownload qshell_qdownload.cfg
3. qshell_qdownload.cfg 内容如下
{
    "dest_dir"   :   "c:\\tmp\\",
    "bucket"     :   "product-scanner",
    "prefix"     :   "",
    "suffixes"   :   ".png,.jpg",
    "cdn_domain" :   "http://owavujdj6.bkt.clouddn.com",
    "referer"    :   "http://www.example.com",
    "log_file"   :   "download.log",
    "log_level"  :   "info",
    "log_rotate" :   1,
    "log_stdout" :   true
}
执行报错：
2017/09/17 00:36:32 [I] Load account from C:\Users\xbyan\.qshell\account.json
2017/09/17 00:36:32 [I] Listing bucket `product-scanner` by prefix ``
Downloading 6939209518020-0.22-862005039630260-2017-09-16 23:46:25.8.jpg [1/30, 3.3%] ...
Downloading 6939209518020-0.26-862005039630260-2017-09-16 23:46:14.7.jpg [2/30, 6.7%] ...
2017/09/17 00:36:32 [I] Downloading 6939209518020-0.22-862005039630260-2017-09-16 23:46:25.8.jpg => c:\tmp\6939209518020-0.22-862005039630260-2017-09-16 23:46:25.8.jpg
Downloading 6939209518020-0.26-862005039630260-2017-09-16 23:46:26.6.jpg [3/30, 10.0%] ...
2017/09/17 00:36:32 [I] Downloading 6939209518020-0.26-862005039630260-2017-09-16 23:46:14.7.jpg => c:\tmp\6939209518020-0.26-862005039630260-2017-09-16 23:46:14.7.jpg
Downloading 6939209518020-0.28-862005039630260-2017-09-16 23:46:26.2.jpg [4/30, 13.3%] ...
2017/09/17 00:36:32 [I] Downloading 6939209518020-0.26-862005039630260-2017-09-16 23:46:26.6.jpg => c:\tmp\6939209518020-0.26-862005039630260-2017-09-16 23:46:26.6.jpg
Downloading 6939209518020-0.29-862005039630260-2017-09-16 23:41:45.7.jpg [5/30, 16.7%] ...
2017/09/17 00:36:32 [I] Downloading 6939209518020-0.28-862005039630260-2017-09-16 23:46:26.2.jpg => c:\tmp\6939209518020-0.28-862005039630260-2017-09-16 23:46:26.2.jpg
Downloading 6939209518020-0.31-862005039630260-2017-09-16 23:46:21.2.jpg [6/30, 20.0%] ...
2017/09/17 00:36:32 [I] Downloading 6939209518020-0.29-862005039630260-2017-09-16 23:41:45.7.jpg => c:\tmp\6939209518020-0.29-862005039630260-2017-09-16 23:41:45.7.jpg
Downloading 6939209518020-0.35-862005039630260-2017-09-16 23:41:09.2.jpg [7/30, 23.3%] ...
Downloading 6939209518020-0.37-862005039630260-2017-09-16 23:40:59.3.jpg [8/30, 26.7%] ...
Downloading 6939209518020-0.38-862005039630260-2017-09-16 23:46:25.0.jpg [9/30, 30.0%] ...
Downloading 6939209518020-0.39-862005039630260-2017-09-16 23:46:16.6.jpg [10/30, 33.3%] ...
Downloading 6939209518020-0.39-862005039630260-2017-09-16 23:46:25.4.jpg [11/30, 36.7%] ...
2017/09/17 00:36:32 [E] Open local file c:\tmp\6939209518020-0.28-862005039630260-2017-09-16 23:46:26.2.jpg.tmp failed open c:\tmp\6939209518020-0.28-862005039630260-2017-09-16 23:46:26.2.jpg.tmp: The filename, directory name, or volume label syntax is incorrect.
2017/09/17 00:36:32 [I] Downloading 6939209518020-0.31-862005039630260-2017-09-16 23:46:21.2.jpg => c:\tmp\6939209518020-0.31-862005039630260-2017-09-16 23:46:21.2.jpg
Downloading 6939209518020-0.4-862005039630260-2017-09-16 23:40:59.7.jpg [12/30, 40.0%] ...
2017/09/17 00:36:32 [E] Open local file c:\tmp\6939209518020-0.26-862005039630260-2017-09-16 23:46:14.7.jpg.tmp failed open c:\tmp\6939209518020-0.26-862005039630260-2017-09-16 23:46:14.7.jpg.tmp: The filename, directory name, or volume label syntax is incorrect.
2017/09/17 00:36:32 [E] Open local file c:\tmp\6939209518020-0.22-862005039630260-2017-09-16 23:46:25.8.jpg.tmp failed open c:\tmp\6939209518020-0.22-862005039630260-2017-09-16 23:46:25.8.jpg.tmp: The filename, directory name, or volume label syntax is incorrect.

**Comment by jemygraw** [comment]
嗯，这个问题是因为 `dest_dir` 的问题，可以写做 `c:\\temp`
