### ISSUE TITLE
建议维护官方可用作 npm script 项目依赖的 npm package

### ISSUE THREAD

**Issue by KingMario** [qiniu/qshell#128]
建议参考或者 fork [qshell-cli](https://github.com/longtian/qshell-cli)，创建可以及时更新的 npm package。

npm package 的好处在该 github repo 的 readme 中有说明：

> 为什么把 qshell 当成一个 NPM 的依赖
> 
> 像 qshell 这样的部署工具一般只有运维人员才会用到，但对于提倡 DevOps 文化的团队来说，把部署工具也放进项目依赖里会非常方便。 这一点也是受到了 12factor 里 显式声明依赖关系 这一条的启发。
> 

也就是普通开发者可以不用关心如下问题：

* 不同操作系统下如何下载 qshell
* 如何进行权限设置
* 如何设置 account（只需要在项目中添加 .qshell/account.json文件即可）
* 如何使用 qshell 批量删除、批量上传、cdnrefsh ……命令（只需要有一个人了解，并编写成相应的 npm scripts 指令即可）

**Comment by jemygraw** [comment]
GIVE ME A PR

**Comment by KingMario** [comment]
建议直接 fork https://github.com/longtian/qshell-cli 然后官方维护啊
或者去把那个 repo 里的代码直接拷贝过来就行了

**Comment by kimown** [comment]
我觉得作为一个cli工具，readmd里面写一堆使用的异常文档，为什么不简洁些，几个命令就能完成基本的功能
有些文档，除了增加字数和提高入门的上手难度，真没看出多少意义。

**Comment by jemygraw** [comment]
@kimown 
>readmd里面写一堆使用的异常文档，为什么不简洁些，几个命令就能完成基本的功能

这个指的是什么？文档详细是为了让人入门方便，只要耐心看，就会用。

**Comment by kimown** [comment]
@jemygraw 
嗯，我明白写文档的重要性，但是也要考虑到新人的上手难度吧，举例说这是 https://hexo.io/ 的文档，它可以简洁到5个命令就能让新人知道做什么
```
npm install hexo-cli -g
hexo init blog
cd blog
npm install
hexo server
```

再看下[READMD.md](https://github.com/qiniu/qshell/blob/master/README.md#安装)，我觉得就这个安装流程就能把一批新人拒之门外，同样qshell也是一个cli工具，为什么不能做到几个命令就能完成基本的任务呢？

**Comment by KingMario** [comment]
鉴于这个库的人看不懂我提的issue，此issue关闭
