### ISSUE TITLE
command not found: qshell

### ISSUE THREAD

**Issue by wuzhenli** [qiniu/qshell#133]
我用的mac，
1、文件名修改 为：qshell    2、添加了 chmod +x 权限    3、在qshell 目录下运行 qshell 提示 “command not found: qshell”。
这是怎么回事？

**Comment by jemygraw** [comment]
./qshell 
你如果希望直接输入qshell就能运行，请把qshell所在目录放入 $PATH  中，具体做法，请看 `README.md` 文档
