### ISSUE TITLE
qupload 正向匹配要上传的文件

### ISSUE THREAD

**Issue by jingwu15** [qiniu/qshell#134]
在使用qupload上传文件时，目前支持根据文件列表及文件模式匹配上传。

方件列表式：
./qshell dircache ./    ./file_list.log
如  ./qshell qupload 10 -file-list ./file_list.log

文件忽略匹配式：
./qshell qupload 10 -skip-file-prefixes py
./qshell qupload 10 -skip-fixed-strings git
./qshell qupload 10 -skip-path-prefixes   www/spider
./qshell qupload 10 -skip-suffixes png

我希望有文件正向匹配模式，即只上传通过规则匹配到的文件，涉及如下几种情况
1. 上传有某后缀的文件
./qshell qupload 10 -with-suffixes png

2. 上传有某前缀的文件
./qshell qupload 10 -with-prefixes spider

3. 上传指定文件夹内的文件
./qshell qupload 10 -with-dirs spider,web,py

4. 只上传相对根目录的文件，忽略子目录：
./qshell qupload 10 -with-only-file ./           

希望可以采纳！

**Comment by jemygraw** [comment]
有个办法可以，你先用 `dircache` 跑一个 `file_list` 参数的列表，然后手动编辑下，删掉你不需要的文件，然后qupload的配置文件里面除了指定你 `dircache`的 `src_dir`之外，再指定参数 `file_list`就可以了。
