### ISSUE TITLE
支持使用go命令直接下载最新版本

### ISSUE THREAD

**Issue by longwdl** [qiniu/qshell#136]
每次有新版本需要手动更新很麻烦，是否可以支持通过`go get`自动下载？

参考其它工具[assh](https://github.com/moul/advanced-ssh-config)。

`go get -u github.com/moul/advanced-ssh-config/cmd/assh`

**Comment by jemygraw** [comment]
我想了想，暂时还是通过手动发布的方式，因为这样至少可以利用七牛cdn保障大家都能下载到。
