### ISSUE TITLE
qupload2的-ignore-dir参数不支持.git目录？

### ISSUE THREAD

**Issue by ohblue** [qiniu/qshell#137]
qshell qupload2 -src-dir=./ -ignore-dir=.git   运行不了

**Comment by jemygraw** [comment]
ignore-dir的含义不是跳过目录，如果需要跳过指定的目录，可以使用 `-skip-path-prefixes` 选项，具体请参考 https://github.com/qiniu/qshell/blob/master/docs/qupload.md
