### ISSUE TITLE
七牛对象存储服务 - fput子命令执行后不会调用CDN缓存刷新API，在使用时存在困扰

### ISSUE THREAD

**Issue by delight09** [qiniu/qshell#138]
使用的是最新发布qshell-linux-x64

[fput.md](https://github.com/qiniu/qshell/blob/master/docs/fput.md)文档中没有提及这个API，[官方upload文档](https://developer.qiniu.com/kodo/api/1312/upload)也没有。但实际上，需要手动调用API。

作为用户，感受到的是使用官方工具成功上传后，给出的 **外链** 没有更新，请考虑改进文档或工具。

详情请见这个帖子：[https://www.v2ex.com/t/404735](https://www.v2ex.com/t/404735)

**Comment by jemygraw** [comment]
覆盖上传文件的话，如果那个文件链接被访问过，有可能在CDN造成缓存，存储里面覆盖之后，需要刷新下那个链接。

**Comment by jemygraw** [comment]
fput命令本身指的是 form upload，就是 https://developer.qiniu.com/kodo/api/1312/upload 所介绍的表单上传。

**Comment by delight09** [comment]
hi Jemy,
请考虑在文档中提及，在更新文件后需要调用API刷新CDN，而不是直接关闭Issue。

请注意有很多用户存在这一困扰，详见：
https://www.v2ex.com/t/404735


谢谢

**Comment by delight09** [comment]
另，经验证：
未访问过的外链，上传新版本覆盖后，确实拿到的是新版本。

**Comment by jemygraw** [comment]
cdn访问过，会缓存文件，这个是常识。

**Comment by delight09** [comment]
hi Jemy,

我用的是**七牛对象存储**服务，调用的是网页控制台**外链**。

工具链文档(archive.is存档)：
[https://developer.qiniu.com/kodo/api/1312/upload](http://archive.is/5qJsf)

[https://github.com/qiniu/qshell/blob/master/docs/fput.md](http://archive.is/QFd1O)

均无法搜索到"CDN"关键词。这不是**常识**，这是使用**七牛对象存储**服务的`深坑`。

做为消费者，我没有必要引起争执，更没有义务提醒你们更新文档。但是事实就摆在那，**七牛对象存储**服务**不**是所见即所得那样**优雅**。至于七牛内部人员看到会怎么做，也都是你们内部决定的。

再次强调，作为消费者，我已经跨过这个`深坑`，我*对此*已经*知足*了。


谢谢

**Comment by delight09** [comment]
附上两张截图，没别的意思，就是强调下文档不够完善的结果罢了(Code和Issues数字比较)

![issue related refresh](http://ww2.sinaimg.cn/large/0060lm7Tly1flhnvo45tqj30t80dedgt.jpg)

![issue related cache](http://ww3.sinaimg.cn/large/0060lm7Tly1flhnvlvvegj30ti0d13zf.jpg)

祝好七牛
以上，
Tue Nov 14 15:50:33 CST 2017

**Comment by jemygraw** [comment]
https://developer.qiniu.com/fusion/kb/1325/refresh-the-cache-and-the-effect-of-time
