### ISSUE TITLE
listbucket的prefix如何支持通配符?

### ISSUE THREAD

**Issue by ohblue** [qiniu/qshell#141]
我这儿有个bucket里边有一个 Uploads/{年-月-日}/ 的prefix
其中年月日不同
我现在要批量删除指定月份，就得先list所有文件，再用grep指定的月份

有没有更简便的方式，比如直接 listbucket 'Uploads/2017-11-*/'  ？？？

**Comment by jemygraw** [comment]
这个不支持通配符，因为API层面不支持通配符。
