### ISSUE TITLE
fetch命令最终保存到七牛文件的key，支持前缀+文件Hash值作为最终文件名

### ISSUE THREAD

**Issue by lzj509649444** [qiniu/qshell#142]
使用fetch命令的时候，文件名= 前缀/文件Hash值，这样的key作为最终文件名

**Comment by jemygraw** [comment]
这个可以分两个步骤来做吧。
1. fetch的时候不用指定文件名，这样的话，会以文件的hash作为文件名
2. 使用move或者batchrename来给这些文件加上一个前缀就好了

**Comment by lzj509649444** [comment]
这是一个方案，不过move错了怎么办，步骤越多越容易出错
