### ISSUE TITLE
listbucket 报错

### ISSUE THREAD

**Issue by Makecodeeasy** [qiniu/qshell#143]
运行 listbucket 报如下错误

2017/12/13 16:52:52 [E] List error for marker `eyJjIjowLCJrIjoiZnJhZ21lbnRzL3oxLnpoYW5xaVRWLjExMjgwMF94Q3VwbC8xNTA3MTkwNTY1NjMxLTE1MD......==`, list timeout, please try later
（ps:上面错误信息中的marker部分用省略号替换了）

请问这个怎么解决？

**Comment by jemygraw** [comment]
网络错误，重试解决。
