### ISSUE TITLE
Win x64 生成缓存列表相对路径有误

### ISSUE THREAD

**Issue by imeilige** [qiniu/qshell#144]
使用dircache生成缓存时应该是相对路径而不是绝对路径

![qiniu](https://user-images.githubusercontent.com/6694281/34047822-86d7e86a-e1ec-11e7-8b69-5f98a4ed1782.jpg)

**Comment by jemygraw** [comment]
谢谢反馈，我们尽快处理

**Comment by jemygraw** [comment]
这个问题大概知道了，其实windows里面如果从命令行传路径的话，不需要两个 `\\` ，只需要：

```
> qshell.exe dircache E:\images\2017\ 
```
这个样子，其中`qupload`也是一样
