### ISSUE TITLE
qshell windows 命令行程序被 chrome 鉴别为带有病毒

### ISSUE THREAD

**Issue by jdhao** [qiniu/qshell#146]
下载 qshell windows 32 位程序，chrome 浏览器提示含有病毒，所以无法下载，什么情况？
![image](https://user-images.githubusercontent.com/16662357/34077685-b35a47da-e344-11e7-86c5-95227b7613ff.png)

**Comment by jemygraw** [comment]
下载最新版本的吧：http://devtools.qiniu.com/qshell-v2.1.7.zip
