### ISSUE TITLE
qshell不是有效命令

### ISSUE THREAD

**Issue by cindyming** [qiniu/qshell#15]
我下载了http://devtools.qiniu.com/qshell-v1.7.0.zip，解压，然后执行的时候尽然报错说qshell不是有效命令 这个是为什么呢？

**Comment by longbai** [comment]
在哪里跑，具体信息麻烦给下

**Comment by cindyming** [comment]
我是在我自己的linuxserver上跑的 

cindy.ming1988@gmail.com

发件人： Bai Long
发送时间： 2016-01-04 15:55
收件人： qiniu/qshell
抄送： Cindy Ming
主题： Re: [qshell] qshell不是有效命令 (#15)
在哪里跑，具体信息麻烦给下

**Comment by cindyming** [comment]
sh qshell_linux_amd64 / can't execute binary file
qshell_linux_amd64 / command not found
但是文件是存在的

**Comment by longbai** [comment]
... 这个不是shell 脚本啊，啊，啊
麻烦chmod +x 改成可执行文件，
没有放入到path 系统变量里面，当然找不到

**Comment by jemygraw** [comment]
如果你希望可以在任意目录下使用qshell，请将qshell工具可执行文件所在目录添加到系统的环境变量中。
