### ISSUE TITLE
系统centos6 64位 无法执行qshell

### ISSUE THREAD

**Issue by feng6961784** [qiniu/qshell#154]
我下载的是qshell-linux-x64
放在我的centos上面，无法执行
![image](https://user-images.githubusercontent.com/10104508/35558088-11eae6c8-05e2-11e8-99f2-bfac539a8824.png)
这个是相应的截图。
一直提示 cannot execute binary file
请问如何解决？谢谢

**Comment by jemygraw** [comment]
![image](https://user-images.githubusercontent.com/1751166/35558296-a1200fee-05e2-11e8-9bcc-eaaeb8e1a1ef.png)
你的系统是32位的，请使用32位的qshell的linux发行版本
