### ISSUE TITLE
listbucket的输出没有对齐

### ISSUE THREAD

**Issue by liyang85** [qiniu/qshell#156]
- 没有对齐的多列输出不方便查看，请对齐。
- 建议提供「仅输出文件名」的选项。

谢谢。

**Comment by jemygraw** [comment]
1. 输出是对齐了的，每个字段tab分隔
2. 如果只需要文件名，可以使用awk切割一下
```
$ qshell listbucket if-pbl stdout |awk -F '\t' '{print $1}'
```

**Comment by liyang85** [comment]
我在macOS上的输出没有对齐：

![image](https://user-images.githubusercontent.com/20695423/36424961-1d6fa372-1680-11e8-92f1-2387230ac8e7.png)

**Comment by jemygraw** [comment]
这个是tab分隔的，显示的问题。

**Comment by liyang85** [comment]
作为用户，输出是什么分隔的不重要，我希望看到的是「显示没有问题」的输出，1个tab明显不能让不同宽度的列对齐，希望开发者能改进。

虽然`listbucket`命令可以正常工作，但由于输出错乱，就像一件漂亮衣服却扣歪了扣子，总让人感觉不够体面。

**Comment by jemygraw** [comment]
这个输出是为了给后面其他的操作用的，可以参考文档来解析这个输出。
