### ISSUE TITLE
qupload 上传时，输出的日志是否与文件上传进度不致

### ISSUE THREAD

**Issue by jingwu15** [qiniu/qshell#159]
在windows使用qupload批量上传文件时，命令行下的输入日志显示已经完成，但查看网络情况还在传输中。这是否是一个Bug。
而且上传完成后，应该是自动退出当前窗口的，却一直没有退出。
我的脚本如下：
`
@echo off
echo “七牛上传中...”

qshell-windows-x86.exe account xxxxxxx xxxxxxxxxxxxxxxxx
qshell-windows-x86.exe qupload 10 up.json`

![qiniu](https://user-images.githubusercontent.com/6680318/38096982-c97450e4-33a6-11e8-994f-226e915e68aa.png)

**Comment by jemygraw** [comment]
那个表示正在上传中，上传完毕之后会有日志打印出来。因为需要支持并发，所以命令行不太好输出进度，只能用这种方式表示一下。
