### ISSUE TITLE
在别的目录调用qshell报错找不到account.json

### ISSUE THREAD

**Issue by jalena** [qiniu/qshell#16]
如果我把qshell放置在/root/下,并且配置了account....

当我在/root/a/目录下执行程序就报错..

> Open account file failed, open .qshell/account.json: no such file or directory ,please use `account` to set AccessKey and SecretKey first

``` sh
~/qshell rput backup nginx_20160213.tar.gz ~/backup/nginx_20160213.tar.gz http://up.qiniug.com
```

**Comment by jemygraw** [comment]
你用的是1.7以上的版本，可以看下readme的说明。

> 对于v1.7.0以上的版本：比如在路径/Users/jemy/Temp/test目录下执行命令，那么使用account设置的账号信息就在/Users/jemy/Temp/test目录下，这种设计的主要目的是方便多账号情况下工具的使用。
