### ISSUE TITLE
qupload 文档有误

### ISSUE THREAD

**Issue by littlee** [qiniu/qshell#161]
关于 src_dir 的值
> 本地同步路径，为全路径格式，工具将同步该目录下面所有的文件；在Windows系统下面使用的时候，注意src_dir的设置遵循D:\\\jemy\\\backup这种方式。也就是路径里面的\要有两个（\\\）

我一直误以为必须填写一个绝对路径，

其实在实际的使用过程中，填写相对路径也是能成功上传的。(在 macOS 和 Windows 都测试过)

```json
{
    "src_dir": "./test",
    "bucket": "my_bucket"
}
```

**Comment by jemygraw** [comment]
填写相对路径是可以，但是考虑到大多数人都会把相对路径写错，所以直接要去写绝对路径，这样更清晰。
