### ISSUE TITLE
qshell listbucket -marker这个要怎么配置？能举个例子吗？

### ISSUE THREAD

**Issue by HuismanKwl** [qiniu/qshell#164]
qshell listbucket -marker <Marker> 这个Marker是什么，要怎么配置？可以举个例子吗

**Comment by jemygraw** [comment]
一般不需要，在list中断的时候，会出现一个marker，下次可以从这个marker开始列举，避免从头再来。

**Comment by HuismanKwl** [comment]
那要-marker这个配置有什么用

**Comment by jemygraw** [comment]
有的时候，因为网络原因导致的中断，会输出一个marker，作为临时的offset，下次可以从这里再次list。
