### ISSUE TITLE
qshell 能否支持读环境变量, 或者全局的account 的配置 ?

### ISSUE THREAD

**Issue by yowenter** [qiniu/qshell#172]
目前的情况:
在每个目录下执行 qshell 前, 都需要设置账户 的 ak 和 sk 信息.
在每个目录下都生成了 .qshell 文件夹

期望:
在在不同目录下, 执行qshell 不需要每次都设置 account. 
![image](https://user-images.githubusercontent.com/6657718/43031191-3f669196-8ccf-11e8-92d6-be5beb7f8796.png)

**Comment by jemygraw** [comment]
如果你不指定 -m 选项就是全局设置的ak，sk
