### ISSUE TITLE
更改文件的MimeType返回403，我的key已经设置了，不知道哪里出了错误

### ISSUE THREAD

**Issue by ZSH-HSZ** [qiniu/qshell#176]
加了qq群但是拒绝添加
![image](https://user-images.githubusercontent.com/31639046/44021973-db7e74da-9f18-11e8-8b24-fe05d076cdcc.png)

**Comment by MistyL** [comment]
确定 account 下有相应 bucket ，同时bucket 中存在相应的 key

**Comment by ZSH-HSZ** [comment]
已解决，没有实名认证
