### ISSUE TITLE
国外服务器中几乎无法下载qshell

### ISSUE THREAD

**Issue by 1265578519** [qiniu/qshell#181]
![1](https://user-images.githubusercontent.com/6442439/44621492-c453dc80-a8d9-11e8-8e31-2d70ae1d1b74.png)

**Comment by 1265578519** [comment]
你们能提供个国外下载节点CDN吗，，不知道上传文件会不会有影响

**Comment by jemygraw** [comment]
国内下载，国外用就好了。
