### ISSUE TITLE
有没有临时设置 AccessKey 和 SecretKey 的方法

### ISSUE THREAD

**Issue by xinshangshangxin** [qiniu/qshell#183]
比如 
`qshell  --ak xxxx --sk xxxx [cmds]`
`--ak` 和 `--sk` 会覆盖 全局/当前目录下 `account` 的配置

主要是临时使用

**Comment by jemygraw** [comment]
使用多用户模式。新建一个目录，然后使用
```
qshell -m account ak sk
```
然后就在这个目录下运行命令。
```
qshell -m rput xxx
```

**Comment by xinshangshangxin** [comment]
不要创建目录

**Comment by xinshangshangxin** [comment]
创建目录比如在 git 下会有一些问题存在
另外一种情况是 比如本身是 给A账户的, 但是由于A账户出现一些问题, 测试B账户是否 有这个问题, 这个时候也不希望用多账户实现

**Comment by i7eo** [comment]
我都是直接 rm -rf account.*
