### ISSUE TITLE
希望下载地址每次都能提供最新版本的下载地址

### ISSUE THREAD

**Issue by CHN-STUDENT** [qiniu/qshell#185]
如题，我打算做一个脚本每次都希望下载你们的最新版本使用。

也就是说希望你们希望你们提供一个类似于 http://devtools.qiniu.com/lastvesrion.zip 这样的下载地址，并且希望有版本号？

不知道你们是否能提供？

谢谢。

**Comment by jemygraw** [comment]
目前是按照版本号发布，你说的那个在cdn环境下有点小问题，就是缓存刷新的问题。

**Comment by CHN-STUDENT** [comment]
话说又想起来有没有通过网页能够获取最新版本版本号或者下载地址？这样也能起到类似的效果
