### ISSUE TITLE
qdownload增量重复下载

### ISSUE THREAD

**Issue by two8g** [qiniu/qshell#191]
qdownload增量重复下载已下载的文件

**Comment by two8g** [comment]
Local file `...` exists, but remote file changed, go to download.
显然，本地备份文件的修改时间与远程文件修改时间不一致

**Comment by jemygraw** [comment]
https://github.com/qiniu/qshell/blob/f1f969e8fb49a5767d309b8a67e2ccfdd2e6ea7d/src/qshell/qdownload.go#L365

这里不是比较文件的本地修改时间，而是上一次下载的时候缓存到leveldb的文件的远端修改时间，比较的是这个远端的修改时间是否一致。
