### ISSUE TITLE
建议：qupload 能实时输出进度

### ISSUE THREAD

**Issue by shaunthegeek** [qiniu/qshell#2]
在 travis-ci.org中执行 `qshell qupload qshell.conf`，长时间没有输出，超时了。

建议：qupload 能实时输出进度，就像 rput 一样。

出错截图：
![2015-07-15 17 53 56](https://cloud.githubusercontent.com/assets/4971414/8695884/c7933818-2b1a-11e5-9340-ade7fdc2e646.png)

**Comment by jemygraw** [comment]
qupload是有输出的，也有进度的。

**Comment by shaunthegeek** [comment]
真没有……那个输出和进度是 总体的，上传完一个文件才输出一次。
上传到一个几百兆的大文件时，会一直停在那里。

**Comment by shaunthegeek** [comment]
就像图中的 827行，行尾显示的 (10/13, 76.9%) 是不会持续变化输出的，直到此文件上传完成，才会变。导致超时

**Comment by jemygraw** [comment]
CLOSE
