### ISSUE TITLE
上传或者其他原因运行失败后应该返回非0的 error code

### ISSUE THREAD

**Issue by xuanyu-h** [qiniu/qshell#20]
上传或者其他原因运行失败后应该返回非0的 error code, use `os.Exit(x)`
方便后续脚本判断运行状态

**Comment by jemygraw** [comment]
这个在哪里返回？

**Comment by xuanyu-h** [comment]
返回给 terminal, 现在 qshell 里面返回的状态值都是 0, 因为全部都使用了 return
我在脚本里使用 `echo $?` 获取不到正确的返回码, 响应的错误应该有响应的返回码

**Comment by jemygraw** [comment]
CLOSE
