### ISSUE TITLE
illegal base64 data

### ISSUE THREAD

**Issue by Gourds** [qiniu/qshell#204]
Version: `v2.3.3`
OS: `Linux ip-10-31-0-168 4.4.41-36.55.amzn1.x86_64 #1 SMP Wed Jan 18 01:03:26 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Problem:
```bash
GetBucketManager: Decrypt account bytes: DecryptSecretKey: illegal base64 data at input byte 0
```

这个是什么情况，数据编码问题？

**Comment by tonycai653** [comment]
使用qshell user clean, 然后重新qshell account ak sk name 记录账户ak/sk信息到本地就可以了；这个是因为2.3.0以后的版本和之前的版本ak/sk内部保存格式不同造成的

**Comment by Gourds** [comment]
@tonycai653  Thanks
