### ISSUE TITLE
在容器内无法使用：Current not implemented on linux/amd64

### ISSUE THREAD

**Issue by TangOwen** [qiniu/qshell#207]
错误提示：get current user: user: Current not implemented on linux/amd64
本机系统：ubuntu 16.04
 (容器系统ubuntu 16.04和centos7)
![image](https://user-images.githubusercontent.com/13010773/49579499-5d899900-f987-11e8-9f5e-3e64050ee0bd.png)

**Comment by tonycai653** [comment]
这个是因为跨平台编译， golang底层用的是cgo获取当前用户的家目录。您可以在自己的linux版本上编译一下，应该可以解决这个错误
