### ISSUE TITLE
写在bash脚本中的时候，qshell无法运行，提示account.json 不存在

### ISSUE THREAD

**Issue by cyberdak** [qiniu/qshell#21]
`cd $BACKUP_DIR
mysqldump $OPTIONS >> $DUMPFILE
echo $OPTIONS
if [[ $? == 0 ]]
then
    tar czvf $ARCHIVE $DUMPFILE >>  $LOGFILE 2>&1
    echo "[$ARCHIVE] Backup Successful!" >> $LOGFILE
    rm -f $DUMPFILE
    /root/qs/qshell account $AK $SK
    /root/qs/qshell fput $QN_ZONE  $ARCHIVE $BACKUP_DIR/$ARCHIVE
else
    echo "Database Backup fail!" >> $LOGFILE
    #mail -s "database : $DATABASE Daily Backup Fail!" $MAIL
fi`

代码如上

执行结果:
`Open account file failed, open .qshell/account.json: not a directory
Open account file failed, open .qshell/account.json: not a directory, please use`account`to set AccessKey and SecretKey first`

**Comment by jemygraw** [comment]
根据提示，首先你得用`qshell account`来设置`accessKey`和`secretKey`，请仔细看文档。

**Comment by Teraflopst** [comment]
设置 `accessKey` 和 `secretKey` 时生成的 `account.json` 要在你的脚本运行 cd 的目录找到才行。
一般在 `~/` 生成，或者在你 使用 `qshell account` 设置时的 cd 目录。
