### ISSUE TITLE
质量方面的一些建议

### ISSUE THREAD

**Issue by CarlJi** [qiniu/qshell#213]
1. 尽可能编译静态的包，这样能较好的在各种容器image环境下使用: http://blog.wrouesnel.com/articles/Totally%20static%20Go%20builds/
2. 修复静态检查的问题，提升代码质量: https://goreportcard.com/report/github.com/qiniu/qshell
3. 构建CI持续体系，针对每一次提交，都执行代码检查，单元测试等。可以使用travis来构建。
4. release包，最好通过固定的构建脚本来做，这样能避免人为失误

**Comment by tonycai653** [comment]
感谢您的建议，后续我们会加上这些完善起来
