### ISSUE TITLE
请问QDownload日志中的Failure会被自动重下么？

### ISSUE THREAD

**Issue by zhbzhbzhbz** [qiniu/qshell#222]
比如
```
2019/01/05 08:03:12.524 [I]    Total:   2188896
2019/01/05 08:03:12.524 [I]    Skipped:         0
2019/01/05 08:03:12.524 [I]    Exists:         0
2019/01/05 08:03:12.524 [I]    Success:   2066107
2019/01/05 08:03:12.524 [I]    Update:         0
2019/01/05 08:03:12.524 [I]    Failure:    122789
2019/01/05 08:03:12.524 [I]    Duration:14h30m58.537614s
```
不知道这些Failure是否会重新下载

**Comment by tonycai653** [comment]
会的

**Comment by zhbzhbzhbz** [comment]
> 会的

感谢
不过好像不都会（虽然我看日志有重新下载了的），因为用Windows自带的文件数量统计是2066120，相比于2188896还差了12万，不知道是因为有大段时间的网络断开还是什么，有很多并没有重新下载（就是二次尝试失败？）。
目前正在重新下载，好在它会跳过下载过的文件，速度很快。
感觉可以把重新下载的逻辑放在末尾再试一次？

**Comment by tonycai653** [comment]
逻辑是这样的，下载过成功的文件本地会记录；重新运行的时候，会监测本地下载过的文件，就跳过，没有下载过的话，就重新下载的

**Comment by zhbzhbzhbz** [comment]
> 逻辑是这样的，下载过成功的文件本地会记录；重新运行的时候，会监测本地下载过的文件，就跳过，没有下载过的话，就重新下载的

好的感谢~ 
感觉可以在"docs/qdownload.md"里标注下~
