### ISSUE TITLE
qshell batchchtype问题咨询

### ISSUE THREAD

**Issue by cjmking2010** [qiniu/qshell#223]
你好，
windows server 2003 r2系统
qshell-v2.3.4
我用 qshell batchchtype 进行存储类型修改的时候发现，文件名里面有空格就会报错，截断在空格部分。
不像qshell chtype里使用“”号就是正常的
例子：
qshell batchchtype iadpic --force -i 1.txt
文件名：
201801/20180101/1630 180101251945660_1.jpg 1
报错：
2019/01/09 15:33:46.562 [E]  Chtype '201801/20180101/1630' => '0' Failed, Code:
612, Error: no such file or directory

**Comment by tonycai653** [comment]
这个是因为最新的版本默认以为空白分割文件的一行的， 包括\t, 空格； 可以重命名下文件，在文件名字中不要有空格

**Comment by cjmking2010** [comment]
要改空格问题影响的数据量就大了。
算了，我们用qshell chtype调整好了。

**Comment by cjmking2010** [comment]
> 
> 
> 这个是因为最新的版本默认以为空白分割文件的一行的， 包括\t, 空格； 可以重命名下文件，在文件名字中不要有空格

要改空格问题影响的数据量就大了。
算了，我们用qshell chtype调整好了。
