### ISSUE TITLE
rput 上传到98%之后 总是失败...

### ISSUE THREAD

**Issue by miaotaizi** [qiniu/qshell#225]
2019/01/23 14:07:20 [W] resumable.Put retrying ...
2019/01/23 14:07:23 [W] resumable.Put retrying ...
Progress: 71.01%2019/01/23 14:08:51 [W] resumable.Put retrying ...
Progress: 73.90%2019/01/23 14:10:29 [W] resumable.Put retrying ...
Progress: 74.48%2019/01/23 14:11:04 [W] resumable.Put retrying ...
Progress: 75.05%2019/01/23 14:11:18 [W] resumable.Put retrying ...
Progress: 79.67%2019/01/23 14:14:00 [W] resumable.Put retrying ...
Progress: 83.71%2019/01/23 14:15:34 [W] resumable.Put retrying ...
Progress: 84.29%2019/01/23 14:16:08 [W] resumable.Put retrying ...
Progress: 85.45%2019/01/23 14:16:46 [W] resumable.Put retrying ...
Progress: 87.18%2019/01/23 14:18:04 [W] resumable.Put retrying ...
2019/01/23 14:18:07 [W] resumable.Put retrying ...
Progress: 88.91%2019/01/23 14:18:34 [W] resumable.Put retrying ...
Progress: 98.27%
Put file error, resumable put failed
Last time: 3011.01 s, Average Speed: 241.3 KB/s

每次执行都是这个结果, 为什么?

**Comment by xushiwei** [comment]
可能是网络问题。历史过久issue。先close，如果当前还存在问题，请reopen issue。
