### ISSUE TITLE
qshell move 失败：Move error: no such bucket

### ISSUE THREAD

**Issue by hide-in-code** [qiniu/qshell#229]
![image](https://user-images.githubusercontent.com/19517597/55713974-5ac9ae00-5a24-11e9-80ef-f6d5b0c00a0d.png)
![image](https://user-images.githubusercontent.com/19517597/55714061-83ea3e80-5a24-11e9-804e-26c327f8e623.png)

**Comment by Mei-Zhao** [comment]
现在move命令当您需要指定move后目标文件名称时，需要使用-k 指定，比如您的需求，如下指令可以解决您的问题：
qshell move if-pbl qiniu.jpg if-pbl -k 2015/01/19/qiniu.jpg，
这次更新没有考虑兼容友好性，我们决定兼容2种姿势，会在下一版本中发布。

**Comment by hide-in-code** [comment]
感谢回复，这个问题后面应该是在本地改名之后重新上传以解决的，近期没有相关的使用需求，后续如果有问题会再次开启issue。

**Comment by hide-in-code** [comment]
非常希望我们的反馈能够快速而有效。国内开源风气全靠我们大家的努力~~
