### ISSUE TITLE
qdownload 下载的图片都只有1K

### ISSUE THREAD

**Issue by tomliy** [qiniu/qshell#23]
在windows系统下， 通过 qdownload 命令执行后，下载到本地的图片文件都只有1K。
而且图片全部打不开

**Comment by jemygraw** [comment]
你看看下载的文件内容，不是图片，估计是报错信息

**Comment by tomliy** [comment]
我这边下载的图片都是jpeg格式。
图片点开都是显示图片查看器无法打开改文件，应为改文件已经损坏，损毁或过大，

**Comment by tomliy** [comment]
{
    "dest_dir"  :   "E:\qiniu_image",
    "bucket"    :   "tangsons",
    "domain"    :   "http://image.tansons.cn",
    "access_key"    :   "XGoncZxNJgVzvdM3UooJBZ5FJ9m1-MdolFc-ha-g",
    "secret_key"    :   "**********************gwE4h9mYvv6Q7ls5u7zCDZj",
    "is_private"    :   false,
    "prefix"    :   "/images/information/"

}
这是qdownload.conf的配置文件。
而且我dos命令行里也没看见报错啊。

**Comment by jemygraw** [comment]
你的域名是不能访问的
