### ISSUE TITLE
如何删除账户

### ISSUE THREAD

**Issue by fuxingjun** [qiniu/qshell#240]
user.md 404了

**Comment by tonycai653** [comment]
把问题具体描述下

**Comment by fuxingjun** [comment]
> 把问题具体描述下

qshell 可以记录多个设置的账户信息，账户的管理，切换，删除等，可以参考qshell user自命令文档
qshell user的文档404了。
https://github.com/qiniu/qshell/blob/master/docs/docs/user.md

**Comment by tonycai653** [comment]
https://github.com/qiniu/qshell/blob/master/docs/user.md 这个地址
