### ISSUE TITLE
qupload文件跳过问题

### ISSUE THREAD

**Issue by hjy2588818** [qiniu/qshell#241]
我的相对路径是：attachment/album/201509/1537512533hkaj7.jpg  我在skip_path_prefixes和skip_fixed_strings都设置了：attachment/album/2015  但是还是被Uploading了，必须写全路径：attachment/album/201509这样么，那太多了

**Comment by tonycai653** [comment]
具体配置文件和遇到的问题，到七牛提工单吧； skip_path_prefixes会跳过前缀， fixed_strings 会只要包含就跳过
