### ISSUE TITLE
下载时随机401

### ISSUE THREAD

**Issue by hide-in-code** [qiniu/qshell#249]
批量下载时随机性的401，同样的地址第一次下载失败，再执行就又好了

**Comment by xushiwei** [comment]
可复现么？我们看下这个问题。

**Comment by hide-in-code** [comment]
感谢回复。当时使用的方式应该是用`qshell get <Bucket> <Key>`的方式，写入一个shell文件，一行一个文件。而不是使用文件列表的方式下载，当时使用的的版本距离现在快一年了，目前已经更新了工具并且近期无相关使用场景，暂时无法复现。后续有问题会再次开启
