### ISSUE TITLE
qupload错误 Invalid cache line 

### ISSUE THREAD

**Issue by yondwell** [qiniu/qshell#26]
# qshell qupload 300 qnconfig.cnf

2016/07/11 21:34:32 [INFO][qshell] qupload.go:232: Use the last cached local sync dir file list ...
2016/07/11 21:34:32 [ERROR][qshell] qupload.go:340: Invalid cache line `14  14412684965838689`

----------Upload Result----------
Total:       0
Success:     0
Failure:     0
Skipped:     0

**Comment by jemygraw** [comment]
你是不是没有src_dir的访问权限。还是文件夹里面没有文件。

**Comment by jemygraw** [comment]
那个，你删除掉 file_list 那个参数，只用 src_dir 就可以了，如果你要用 file_list 那么，可以用 dircache 命令来跑一个列表。

**Comment by yondwell** [comment]
已经解决 src_dir 不能使用软连接,使用真实路径就没问题了

**Comment by namiwang** [comment]
请问这个不支持 symlink 的问题有计划修复嘛

**Comment by jemygraw** [comment]
@nanowang 这个目前不打算支持软链接，因为会引入复杂性问题，比如文件的名称就不太好定义。
