### ISSUE TITLE
文件没有签名Mac下执行直接就被干掉了

### ISSUE THREAD

**Issue by ipconfiger** [qiniu/qshell#262]
RT

**Comment by jeffguorg** [comment]
设置里面应该可以同意执行的

**Comment by Mei-Zhao** [comment]
您好，qshell MacOS可执行程序目前没有提交到Apple公正，未获得Developer ID 证书，您可以在系统偏好设置->安全与隐私   界面同意程序的运行。后续我们会推动Developer ID 证书签名的事情，内部建立issue跟踪，内部issue编号KODO-10279

**Comment by miyunda** [comment]
先用finder打开一次，然后就可以用命令行了
