### ISSUE TITLE
Error: unknown command "prefetch" for "qshell"

### ISSUE THREAD

**Issue by declantsien** [qiniu/qshell#265]
` qshell prefetch`

Error: unknown command "prefetch" for "qshell"
Run 'qshell --help' for usage.
unknown command "prefetch" for "qshell"

` qshell -v`
qshell version v2.4.1

**Comment by forrest-mao** [comment]
目前 qshell 确实不支持对象存储的强制镜像回源 prefetch 功能（https://developer.qiniu.com/kodo/api/1293/prefetch），我们看是否可以加上
如果您这边是需要 CDN 的预取功能，可以使用 cdnprefetch 来操作，文档详见 https://github.com/qiniu/qshell/blob/master/docs/cdnprefetch.md

**Comment by Mei-Zhao** [comment]
我们后续会修复存储强制镜像回源功能prefetch命令，内部已经建立issue跟踪，内部issue编号KODO-10272

**Comment by bachue** [comment]
已经解决
