### ISSUE TITLE
加上 Codecov, Travis, etc 并持续改进

### ISSUE THREAD

**Issue by xushiwei** [qiniu/qshell#270]
参考 https://github.com/qiniu/goplus/blob/master/README.md

![image](https://user-images.githubusercontent.com/396972/86246618-dc839980-bbdd-11ea-99df-bbf98ee09ddb.png)

**Comment by CarlJi** [comment]
Refer #271 , 该PR已经处理了部分。

考虑到github action出色的模块组合能力，这里用github action替代了travis，效果看起来不错:
![image](https://user-images.githubusercontent.com/10810759/86266354-ab17c780-bbf7-11ea-8526-1965b7a2a480.png)
后续计划在所有七牛开源REPO上都使用action。

同样针对本repo，还会继续支持自动打包release版本的能力，方面做到更优雅的发布等能力，故这个issue继续hold。
/hold

**Comment by xushiwei** [comment]
关于自动打包 release 能力，这个可以单独建立一个 issue

**Comment by CarlJi** [comment]
参考 #273 ，目前通过github release qshell，会自动给其二进制注入版本号。至于后续的版本兼容性，将会推动相关产品负责人进行统一规划。
