### ISSUE TITLE
qupload和qupload2无法上传文件夹下最新文件

### ISSUE THREAD

**Issue by ClassWizard** [qiniu/qshell#283]
#### 问题描述
使用qupload和qupload2上传时，源文件夹下新生成的文件并不会被上传。
连跳过判断都没有执行。貌似有一个缓存列表来确定上传文件。
$HOME/.qshell/qupload

尝试删除该文件夹下的*/*.cache文件后就可以了。

#### 重现步骤

1. qupload或qupload上传
2.源文件夹中添加新文件 
3. 再次上传，新的文件不会上传（第一步检查skip就没有）

#### 期望结果？

能够正确同步上传

#### 实际结果？

新加入的文件都不会处理

#### 错误日志/截图/配置参数 
第一次上传，文件目录其实有两个新文件夹（1700和1701），但是没有处理.
![企业微信截图_ee9af72b-ef21-46e4-a4d2-967837b5c334](https://user-images.githubusercontent.com/9192855/90865833-953bad00-e3c5-11ea-8638-0b4ad7de5f80.png)
删除缓存后，正常处理了所有文件
![企业微信截图_1bbc9d79-f0e2-47b4-88de-ffaa63b0714c](https://user-images.githubusercontent.com/9192855/90866933-2c553480-e3c7-11ea-8f03-73ee2a9686f4.png)

#### 相关环境信息
- **操作系统**：macOS 10.15.6 (19G73)
- **qshell版本**: qshell version v2.4.1

**Comment by webshi** [comment]
你的 qshell.json 中配置了 rescan_local 这个参数没，这个参数用于同步本地新增文件

**Comment by ClassWizard** [comment]
之前没有配置，配置后正常了

**Comment by LHshooter** [comment]
我也遇到了无法上传最新文件问题，还在扫描我上一次上传的文件，上次传的没在了直接就报错了
Error stat local file xxx/upload7niu/ota_xxx_t123456789.zip due to 'stat xxx/upload7niu/ota_xxx_t123456789.zip: no such file or directory'。 我本次传的是xxx/upload7niu/ota_xxx_t1602676708.zip，但是却扫描上一次的

**Comment by forrest-mao** [comment]
使用 rescan_local 的时候会将之前没有在列表中的文件补充到待上传的列表中，属于新增的操作，对历史的列表不会做替换，所以如果原始文件不存在，还是会尝试上传，但是读不到文件的话就会报错，其实如果文件不存在是符合预期的话，可以忽略这个报错；
您如果希望扫描每次文件都是最新的列表，可以直接将 qshell 执行路径下的 .qshell/.qupload 隐藏目录清空，就可以扫描最新的文件夹列表了
