### ISSUE TITLE
qshell delete 还是可以通过下线链接下载 

### ISSUE THREAD

**Issue by SmallShooter** [qiniu/qshell#285]
#### 问题描述

使用如下命令（qshell delete smartwatch mm.txt ）对 mm.txt 删除后，通过 （qshel listbucket2 --prefix mm --suffixes txt smartwatch）是不能查到了，但是下载链接还是正常的（https://smartwatch.qiniucdn.com/mm.txt）

#### 重现步骤

1.  上传一个文件到7牛，qshel listbucket2 --prefix mm --suffixes txt smartwatch 是可以查到mm文件
2.  qshell delete smartwatch mm.txt 将mm.txt文件删除
3.  qshel listbucket2 --prefix mm --suffixes txt smartwatch 是不能再查到mm文件，但是通过 https://smartwatch.qiniucdn.com/mm.txt 查看文件是正常的

#### 期望结果？

- https://smartwatch.qiniucdn.com/mm.txt  这个下载链接应该也是失效的，也就是实际空间是删除的

#### 实际结果？

-  https://smartwatch.qiniucdn.com/mm.txt  这个下载链接还是有效

#### 相关环境信息
- **操作系统**：  win10
- **qshell版本**:  qshell version v2.4.1

**Comment by bachue** [comment]
@LHshooter  这是预期的，删除源文件并不会导致 CDN 的缓存被刷新，需要调用 `qshell cdnrefresh` 再刷新一次 CDN。
