### ISSUE TITLE
请问是否有指定对象存储中的404文件的接口？

### ISSUE THREAD

**Issue by tootal** [qiniu/qshell#293]
#### 需求描述

网页端可以指定，但希望有一个命令行的接口来自动化执行。

#### 其他相关建议

404文件既然也是要存储在容器中的，希望能直接指定容器中的文件，而不是（像网页端一样）单独上传。

**Comment by Mei-Zhao** [comment]
您好，404文件在存储空间（应该就是您说的容器）中是一个特殊文件，文件名称固定为errno-404，控制台上传是上传一个固定名称为errno-404，内容是您指定的文件。

如果您希望用存储空间中某个文件作为404文件可以文件重命名一下https://github.com/qiniu/qshell/blob/master/docs/move.md。

如果您希望这个文件保持当前文件名称，您可以copy一下，目标文件名称为errno-404也可以https://github.com/qiniu/qshell/blob/master/docs/copy.md。
