### ISSUE TITLE
qshell cdnrefresh命令怎么从终端里读取内容

### ISSUE THREAD

**Issue by ethanyou725** [qiniu/qshell#296]
文档上说如果没有制定输入文件默认从终端读取输入内容
https://github.com/qiniu/qshell/blob/master/docs/cdnrefresh.md
能否增加个example

qshell version v2.4.1
系统: linux

**Comment by coderlfm** [comment]
同问

**Comment by capraynor** [comment]
这特么项目跟死了一样没人回复。

**Comment by bachue** [comment]
@capraynor @coderlfm @ethanyou725 
```
cat torefresh.txt | qshell cdnrefresh
```
