### ISSUE TITLE
无法上传文件（找不到 AccessKey）

### ISSUE THREAD

**Issue by ImSingee** [qiniu/qshell#298]
#### 问题描述

已经利用 `qshell account`  设定了 Token，在调用上传命令时提示 

Form upload file XXX => XXX failed due to nerror `query region error, app/accesskey is not found`

#### 重现步骤

1.  下载最新版本 qshell
2. 利用 qshell account 配置 Token
3. 调用 qshell qupload/qupload2 上传文件

#### 期望结果？

可以正常上传

#### 实际结果？

无法上传

#### 错误日志/截图/配置参数 

```
> qshell account
Name: NNNN
AccessKey: XXXX
SecretKey: YYYY

> qshell qupload2 --src-dir="$(pwd)/dist" --bucket=xxx --overwrite --rescan-local --log-file /dev/stdout
......
2021/01/06 13:41:32.991 [E] Form upload file XXX => XXX failed due to nerror `query region error, app/accesskey is not found`
......
```

#### 相关环境信息
- **操作系统**：Darwin MacBook-Pro.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64
- **qshell版本**: qshell version v2.4.1

**Comment by gebin** [comment]
这个问题怎么解决呢？

**Comment by bachue** [comment]
先关掉了，如果发现新版本还有相同的问题，可以开新的 issue

**Comment by enjoyWeb** [comment]
> 先关掉了，如果发现新版本还有相同的问题，可以开新的 issue

怎么解决也没说，怎么就关掉呀

**Comment by bachue** [comment]
@enjoyWeb 这种错误一般都是 ak sk 错误，如果还有问题，可以和技术支持沟通。

**Comment by enjoyWeb** [comment]
╭(╯3╰)╮亲！你的信件我已经收到了，我会尽快查看的O(∩_∩)O哈！
