### ISSUE TITLE
建议：下载链接中别用空格

### ISSUE THREAD

**Issue by shaunthegeek** [qiniu/qshell#3]
现在的下载链接中有空格，是这样的：
http://qdisk.qiniudn.com/qshell%20v1.4.5.zip

建议别用空格，按照github release惯例（比如 https://github.com/wifidog/wifidog-gateway/releases ），变成这样：
http://qdisk.qiniudn.com/qshell-1.4.5.zip

**Comment by jemygraw** [comment]
嗯，后面改进下。

**Comment by jemygraw** [comment]
新版本已经改进。
