### ISSUE TITLE
建议加上 batchdelete 可以按  prefix 删除

### ISSUE THREAD

**Issue by bastengao** [qiniu/qshell#30]
通常都要先根据 prefix  listbucket, 然后在根据 list 来删除，比较麻烦。可以一步直接根据 prefix 删除。

**Comment by jemygraw** [comment]
逻辑上这种做法是不对的，因为有时候列表不是根据 listbucket 产生的，所以 batchdelete 只是提供了一种功能，而不用关心列表来源。

**Comment by bastengao** [comment]
我明白你的意思，保持命令的独立和解耦。但是这样缺乏用户体验，就像删除文件夹一样，你不需要把文件夹的所有文件列出来，放到一个文件里，然后再执行另一个命令去读取这个文件，挨个删除文件。你只需要 `rm -r dir`。 估计有很多人有我这样的痛苦。

**Comment by jemygraw** [comment]
命令行工具其本身就是一种运维的工具，缺乏普通用户体验的舒适度，很多人都会双击打开的情况下，唯一的方案就是图形化，不过需求那么多，没办法保持工具简洁的同时，功能连贯。
