### ISSUE TITLE
qshell 命令启动报错

### ISSUE THREAD

**Issue by zyqcoder** [qiniu/qshell#307]
#### 问题描述

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/amy/Documents/software/qiniu/qshell/qshell
  Expected in: flat namespace

#### 重现步骤

1.  正常操作配置后执行qshell命令出现以上问题
2. 
3. 

#### 期望结果？

-请问如何解决

#### 实际结果？

-得到解决

#### 错误日志/截图/配置参数 

![image](https://user-images.githubusercontent.com/16498526/115329005-2cab0700-a1c4-11eb-80c8-6811f941b46e.png)

#### 相关环境信息
- **操作系统**：10.11.6 (15G1212)
- **qshell版本**:v2.5.1

**Comment by YangSen-qn** [comment]
@zyqcoder qshell v2.5.1 需要 macOS 10.12 以上
