### ISSUE TITLE
qshell 没有批量上传目录的命令吗？

### ISSUE THREAD

**Issue by Cinux-Chosan** [qiniu/qshell#310]
#### 需求描述

我希望执行一条命令直接上传打包目录到对象存储，在 qshell 文档中搜了一下发现只有单个文件上传的，没有可以直接批量上传目录的命令，这种需求难道不是很常见吗？一般都是希望上传整个打包目录吧。这个功能 qshell 有直接提供吗？还是说这个功能要自己写 shell 脚本配合 qshell 才能达到效果？

**Comment by YangSen-qn** [comment]
@Cinux-Chosan qupload 和 qupload2 指令支持上传文件夹内文件
