### ISSUE TITLE
使用qshell upload命令回调接口参数含义？

### ISSUE THREAD

**Issue by ljm653467080** [qiniu/qshell#312]
使用qshell upload命令上传一个文件目录，使用到--callback-host和--callback-urls参数，回调有成功，但是回调接口返回的参数只有key和hash值，这两个值有什么含义? 什么命令可以判断一个目录下的所有文件都已经全部上传到七牛云上了呢？

**Comment by bachue** [comment]
key 是上传到云存储的文件的 key，hash 是该文件的 etag 值

**Comment by YangSen-qn** [comment]
qshell qupload [-c <ThreadCount>] [--sucess-list <SuccessFileName>] [--failure-list <FailureFileName>] [--overwrite-list <OverFileName>] [--callback-urls <CallbackUrls>] [--callback-host <CallbackHost>]
<LocalUploadConfig>

上传成功的文件列表会被保存在文件中，文件名通过 --sucess-list  指定；失败的文件列表也会被保存在文件中，文件名通过 --failure-list  指定；
命令结束后，可以通过查看失败的文件列表，如果不存在则均上传成功。成功的文件列表显示了那些文件被上传到七牛云。
@ljm653467080
