### ISSUE TITLE
这个工具有毒吧，我列出bucket中所有文件，一个小时就给我列出来几百个？？？？？？

### ISSUE THREAD

**Issue by tz1390** [qiniu/qshell#313]
#### 重现步骤

1.  
2. 
3. 

#### 期望结果？

-

#### 实际结果？

-

#### 相关环境信息
- **操作系统**：
- **qshell版本**:

**Comment by Jessie-shsh** [comment]
@tz1390 你好！麻烦按上述模板，提交更为具体的信息，方便问题排查和定位
