### ISSUE TITLE
Failed to query region when using qupload

### ISSUE THREAD

**Issue by jeffguorg** [qiniu/qshell#314]
OS:
macOS 11.3.1 (20E241)

Version(https://github.com/qiniu/qshell/releases/tag/v2.6.0):
```
$ ~/.local/bin/qshell version
v2.6.0
```

Config: 
```json
{
    "src_dir"            :   "./public/",
    "bucket"             :   "$BUCKET",
    "overwrite"          :   true,
    "check_exists"       :   true,
    "check_hash"         :   true,
    "check_size"         :   true,
    "rescan_local"       :   true
 }
```

Error in log: 
```log
2021/05/20 14:10:42.274 [I]  Uploading file $SRC: $DST
2021/05/20 14:10:42.275 [E]  Form upload file `$SRC` => `$DST` failed due to nerror `query region error, Get "uc.qbox.me/v2/query?ak=$AK&bucket=$BUCKET&": unsupported protocol scheme ""`
```

**Comment by YangSen-qn** [comment]
@jeffguorg 在当前用户目录下的 .qshell.json 中配置 uc host 时添加 https:// 以规避此问题；同时后续会发版本处理这个问题，感谢您的反馈。

**Comment by jonny77** [comment]
> @jeffguorg 在当前用户目录下的 .qshell.json 中配置 uc host 时添加 https:// 以规避此问题；同时后续会发版本处理这个问题，感谢您的反馈。

能有完整的配置吗. 我也遇到这个问题.蛋疼

**Comment by YangSen-qn** [comment]
在 v2.6.0 中，在 ~/.qshell.json 文件中配置 uc 时需要加 https://
注：
- 在公有云中下述 hosts 可不配置
- host 均为示例，请根据实际情况配置
```
{
    "hosts": {
        "rs": "rs-test.qiniu.com",
        "io": "io-test.qiniu.com",
        "uc": "https://uc-test.qiniu.com", 
        "api": "api-test.qiniu.com",
        "up": "up-test.qiniu.com",
        "rsf": "rsf-test.qiniu.com"
    }
}
```
@jonny77

**Comment by typ431127** [comment]
> 在 v2.6.0 中，在 ~/.qshell.json 文件中配置 uc 时需要加 https://
> 注：
> 
> * 在公有云中下述 hosts 可不配置
> * host 均为示例，请根据实际情况配置
> 
> ```
> {
>     "hosts": {
>         "rs": "rs-test.qiniu.com",
>         "io": "io-test.qiniu.com",
>         "uc": "https://uc-test.qiniu.com", 
>         "api": "api-test.qiniu.com",
>         "up": "up-test.qiniu.com",
>         "rsf": "rsf-test.qiniu.com"
>     }
> }
> ```
> 
> @jonny77

这个配置貌似是测试的域名，我现在配置uc为https://uc.qbox.me 但是又报错token错误
我的.qshell.json
```
{
    "hosts": {
        "rs": "https://rs.qbox.me",
        "io": "https://io.qbox.me",
        "uc": "https://uc.qbox.me",
        "api": "https://api.qbox.me",
        "up": "https://up.qbox.me",
        "rsf": "https://rsf.qbox.me"
    }
}
```
**日志报错**
```
failed due to nerror `bad token`
```

**Comment by YangSen-qn** [comment]
@typ431127 
除了 uc 其他可以不配置

**Comment by typ431127** [comment]
> @typ431127
> 除了 uc 其他可以不配置

我把其他的删除，只保留uc，这个时候还是报错uc错误
```
{
    "hosts": {
        "uc": "https://uc.qbox.me",
    }
}

```
>failed due to nerror `query region error, Get "uc.qbox.me/v2/query?ak=xxxxxxx&bucket=xxxxxxx&": unsupported protocol scheme ""`

**Comment by jeffguorg** [comment]
我上传的场景是gatsby/nodejs构建的静态站点上传以后刷新CDN，所以我用nodejs重新写了整个构建pipeline。🤣

@typ431127  如果可以的话用sdk写脚本吧，不方便用脚本的就回退一个版本吧🤣

**Comment by typ431127** [comment]
> 我上传的场景是gatsby/nodejs构建的静态站点上传以后刷新CDN，所以我用nodejs重新写了整个构建pipeline。🤣
> 
> @typ431127 如果可以的话用sdk写脚本吧，不方便用脚本的就回退一个版本吧🤣

上传单个文件用sdk倒是可以，我目录是自动同步到阿里oss的，因为我现在需要同步到多个存储，阿里云，又拍云都搞定了，就差七牛云了，我不想写代码了，就想让他对比同步，没事，我等他优化一版

**Comment by jonny77** [comment]
"rs":  
        "io":  
        "uc":  
        "api":  
        "up": 
        "rsf":  这几个分别是什么意思???

**Comment by YangSen-qn** [comment]
请使用 v2.6.1

**Comment by jeffguorg** [comment]
@YangSen-qn Mac上2.6.1正常
