### ISSUE TITLE
urlencode函数有错误

### ISSUE THREAD

**Issue by bingqichen** [qiniu/qshell#315]
#### 问题描述
如题，urlencode 函数遇到空格时，会编码为 `+`

#### 重现步骤
执行如下代码
```bash
qshell urlencode "remove node.gif"
# 输出结果：remove+node.gif
```

#### 期望结果？
理论上应该是`remove node.gif` 或者 `remove%20node.gif`

#### 相关环境信息
- **操作系统**：macos
- **qshell版本**: 2.6.0

**Comment by YangSen-qn** [comment]
请使用 v2.6.1
