### ISSUE TITLE
mac 下没有办法运行呀...

### ISSUE THREAD

**Issue by BZbyr** [qiniu/qshell#32]
<img width="510" alt="1" src="https://cloud.githubusercontent.com/assets/12187900/18031156/070e88a2-6d06-11e6-877d-9fa2a98e347d.png">

**Comment by jemygraw** [comment]
这个不是打印出帮助信息了么？后面跟上命令就可以运行了。

**Comment by parallelopipedon** [comment]
我也不太懂, 先打开了qshell, 然后立即就exit了.

exit后没有办法跟上命令啊
