### ISSUE TITLE
qshell batchdelete如何批量删除空间指定前缀名文件

### ISSUE THREAD

**Issue by karmalove** [qiniu/qshell#326]
#### 问题描述
qshell batchdelete如何批量删除空间指定前缀名文件

#### 重现步骤

1.  
2. 
3. 

#### 期望结果？

-

#### 实际结果？

-

#### 相关环境信息
- **操作系统**：Mac os 11.5.2
- **qshell版本**:qshell version v2.6.2

**Comment by YangSen-qn** [comment]
@karmalove 
可以参考这里的文档：
https://github.com/qiniu/qshell/blob/master/docs/batchdelete.md
