### ISSUE TITLE
修改完 MimeType 后， 为何content-type 没变？

### ISSUE THREAD

**Issue by W-quan** [qiniu/qshell#329]
#### 问题描述

测试上传的视频名称是  XXX.png， 实际是个mp4文件。 返回的content-type 是 image/png

通过qshell 修改 mimetype 为 video/mp4后， content-type没有变化。 要怎么才能修改content-type?

**Comment by YangSen-qn** [comment]
请确认下 mimetype 是否修改成功，可以在对象存储 -> 空间 -> 文件管理 中查看最终 mimetype

**Comment by W-quan** [comment]
用 qshell stat 查看是修改了的

**Comment by YangSen-qn** [comment]
@W-quan 有链接吗

**Comment by W-quan** [comment]
https://img.kuaixiangwl.com/picture_9526.png

**Comment by bachue** [comment]
@W-quan 看上去应该是 CDN 缓存导致的，通过在 URL 末尾追加一些参数就能看到实际上 CONTENT-TYPE 已经被改成 video/mp4 了，建议你这边手动刷新下 CDN 缓存。

**Comment by W-quan** [comment]
但是文件类型识别是个问题
