### ISSUE TITLE
Windows 2.7.0 版本上传报错

### ISSUE THREAD

**Issue by mpetrel** [qiniu/qshell#340]
#### 问题描述
最新版本（windows-amd64 v2.7.0)上传有问题，指定文件夹上传后，它把路径重复拼接了，导致上传的时候报错

#### 重现步骤

1. 使用命令 qshell qupload2 --src-dir=F:\\test\\folder --bucket=test --key-prefix=test/path/ --overwrite=true --thread-count=10

#### 期望结果？
将folder文件夹下的所有文件上传至 test/path/ 路径下

#### 实际结果？
例如对于folder文件夹下的 1.txt 文件：
上传报错，qshell 读取文件的路径变成  **F:\test\folder\F:\test\folder\1.txt**
前缀也变成  **test/path/F:/test/folder/1.txt**

使用 2.6.3 版本正常

#### 相关环境信息
- **操作系统**：windows
- **qshell版本**: v2.7.0    amd64

**Comment by YangSen-qn** [comment]
感谢您的反馈，我们会尽快确认问题

**Comment by YangSen-qn** [comment]
@mpetrel 我们这边没有复现到，请您提供下复现的 Debug 日志（增加 -d 选项），上传的文件数量尽可能小，这样方便排查问题

**Comment by mpetrel** [comment]
2022/06/02 09:50:49.509 [A]  Writing log to file:C:\Users\Larry\.qshell\users\yuan\qupload\f0258c49fd08de0df8754e41351d3274\log.txt 


2022/06/02 09:50:49.509 [D]  record root: C:\Users\Larry\.qshell\users\yuan\qupload\f0258c49fd08de0df8754e41351d3274
2022/06/02 09:50:49.510 [I]  upload status db file path:C:\Users\Larry\.qshell\users\yuan\qupload\f0258c49fd08de0df8754e41351d3274\.ldb
2022/06/02 09:50:49.511 [D]  Walk `F:\\test` start from 2022-06-02 09:50:49.510504 +0800 CST m=+0.075996901
2022/06/02 09:50:49.511 [D]  Walking through `F:\\test`
2022/06/02 09:50:49.511 [D]  cacheRootPath:`F:\\test` path:`F:\test\h264_720p.mp4` relativePath:`F:\test\h264_720p.mp4`
2022/06/02 09:50:49.511 [D]  Meet file `F:\test\h264_720p.mp4`, size: 46403015, modtime: 16537947588968142
2022/06/02 09:50:49.511 [D]  cacheRootPath:`F:\\test` path:`F:\test\new_start.jpg` relativePath:`F:\test\new_start.jpg`
2022/06/02 09:50:49.511 [D]  Meet file `F:\test\new_start.jpg`, size: 11478935, modtime: 16535504701972076
2022/06/02 09:50:49.512 [D]  Walk `F:\\test` end at 2022-06-02 09:50:49.512089 +0800 CST m=+0.077581901
2022/06/02 09:50:49.512 [D]  Walk `F:\\test` last for 1.585ms
2022/06/02 09:50:49.512 [D]  Total file count cached 2
2022/06/02 09:50:49.516 [D]  work flow did start
2022/06/02 09:50:49.518 [D]  work consumer 9 start
2022/06/02 09:50:49.518 [D]  work consumer 6 start
2022/06/02 09:50:49.518 [D]  work consumer 4 start
2022/06/02 09:50:49.518 [D]  work consumer 0 start
2022/06/02 09:50:49.518 [D]  work consumer 1 start
2022/06/02 09:50:49.518 [D]  work consumer 2 start
2022/06/02 09:50:49.518 [D]  work consumer 3 start
2022/06/02 09:50:49.518 [D]  work producer start
2022/06/02 09:50:49.518 [D]  work consumer 7 start
2022/06/02 09:50:49.518 [D]  Key:test/path/F:/test/h264_720p.mp4 FileSize:46403015 ModifyTime:16537947588968142
2022/06/02 09:50:49.518 [D]  work consumer 5 start
2022/06/02 09:50:49.518 [D]  work consumer 8 start
2022/06/02 09:50:49.521 [D]  Key:test/path/F:/test/new_start.jpg FileSize:11478935 ModifyTime:16535504701972076
2022/06/02 09:50:49.521 [D]  work producer   end
2022/06/02 09:50:49.521 [D]  work consumer 3   end
2022/06/02 09:50:49.521 [D]  work consumer 4   end
2022/06/02 09:50:49.521 [D]  work consumer 2   end
2022/06/02 09:50:49.521 [D]  work consumer 1   end
2022/06/02 09:50:49.521 [D]  work consumer 0   end
2022/06/02 09:50:49.521 [D]  work consumer 5   end
2022/06/02 09:50:49.521 [D]  work consumer 8   end
2022/06/02 09:50:49.521 [D]  work consumer 7   end
2022/06/02 09:50:49.521 [A]  Uploading F:\test\F:\test\h264_720p.mp4 [1/2, 50.0%] ...
2022/06/02 09:50:49.521 [A]  Uploading F:\test\F:\test\new_start.jpg [2/2, 100.0%] ...
2022/06/02 09:50:49.526 [D]  upload: start upload:F:\test\F:\test\h264_720p.mp4 => [timepano:test/path/F:/test/h264_720p.mp4]
2022/06/02 09:50:49.526 [D]  upload: start upload:F:\test\F:\test\new_start.jpg => [timepano:test/path/F:/test/new_start.jpg]
2022/06/02 09:50:49.526 [D]  resume v1 upload:F:\test\F:\test\h264_720p.mp4 => [timepano:test/path/F:/test/h264_720p.mp4]
2022/06/02 09:50:49.526 [D]  resume v1 upload:F:\test\F:\test\new_start.jpg => [timepano:test/path/F:/test/new_start.jpg]
2022/06/02 09:50:49.526 [D]  upload:   end upload:F:\test\F:\test\h264_720p.mp4 => [timepano:test/path/F:/test/h264_720p.mp4] error:resume v1 upload: open file error:open F:\test\F:\test\h264_720p.mp4: The filename, directory name, or volume label syntax is incorrect.
2022/06/02 09:50:49.526 [E]  Upload  failed:F:\test\F:\test\h264_720p.mp4 => [timepano:test/path/F:/test/h264_720p.mp4] error:upload error:resume v1 upload: open file error:open F:\test\F:\test\h264_720p.mp4: The filename, directory name, or volume label syntax is incorrect.
2022/06/02 09:50:49.526 [D]  upload:   end upload:F:\test\F:\test\new_start.jpg => [timepano:test/path/F:/test/new_start.jpg] error:resume v1 upload: open file error:open F:\test\F:\test\new_start.jpg: The filename, directory name, or volume label syntax is incorrect.
2022/06/02 09:50:49.526 [E]  Upload Failed, F:\test\h264_720p.mp4	46403015	16537947588968142 error:upload error:resume v1 upload: open file error:open F:\test\F:\test\h264_720p.mp4: The filename, directory name, or volume label syntax is incorrect.
2022/06/02 09:50:49.526 [E]  Upload  failed:F:\test\F:\test\new_start.jpg => [timepano:test/path/F:/test/new_start.jpg] error:upload error:resume v1 upload: open file error:open F:\test\F:\test\new_start.jpg: The filename, directory name, or volume label syntax is incorrect.
2022/06/02 09:50:49.526 [D]  work consumer 9   end
2022/06/02 09:50:49.526 [E]  Upload Failed, F:\test\new_start.jpg	11478935	16535504701972076 error:upload error:resume v1 upload: open file error:open F:\test\F:\test\new_start.jpg: The filename, directory name, or volume label syntax is incorrect.
2022/06/02 09:50:49.526 [D]  work consumer 6   end
2022/06/02 09:50:49.526 [D]  work flow did end
2022/06/02 09:50:49.526 [A]  --------------- Upload Result ---------------
2022/06/02 09:50:49.526 [A]                Total:         2
2022/06/02 09:50:49.526 [A]              Success:         0
2022/06/02 09:50:49.526 [A]              Failure:         2
2022/06/02 09:50:49.526 [A]            Overwrite:         0
2022/06/02 09:50:49.526 [A]         NotOverwrite:         0
2022/06/02 09:50:49.526 [A]              Skipped:         0
2022/06/02 09:50:49.526 [A]             Duration:      14.7543ms
2022/06/02 09:50:49.526 [A]  ---------------------------------------------
2022/06/02 09:50:49.526 [A]  See upload log at path:C:\Users\Larry\.qshell\users\yuan\qupload\f0258c49fd08de0df8754e41351d3274\log.txt

**Comment by YangSen-qn** [comment]
> 2022/06/02 09:50:49.509 [A] Writing log to file:C:\Users\Larry.qshell\users\yuan\qupload\f0258c49fd08de0df8754e41351d3274\log.txt
> 
> 2022/06/02 09:50:49.509 [D] record root: C:\Users\Larry.qshell\users\yuan\qupload\f0258c49fd08de0df8754e41351d3274 2022/06/02 09:50:49.510 [I] upload status db file path:C:\Users\Larry.qshell\users\yuan\qupload\f0258c49fd08de0df8754e41351d3274.ldb 2022/06/02 09:50:49.511 [D] Walk `F:\\test` start from 2022-06-02 09:50:49.510504 +0800 CST m=+0.075996901 2022/06/02 09:50:49.511 [D] Walking through `F:\\test` 2022/06/02 09:50:49.511 [D] cacheRootPath:`F:\\test` path:`F:\test\h264_720p.mp4` relativePath:`F:\test\h264_720p.mp4` 2022/06/02 09:50:49.511 [D] Meet file `F:\test\h264_720p.mp4`, size: 46403015, modtime: 16537947588968142 2022/06/02 09:50:49.511 [D] cacheRootPath:`F:\\test` path:`F:\test\new_start.jpg` relativePath:`F:\test\new_start.jpg` 2022/06/02 09:50:49.511 [D] Meet file `F:\test\new_start.jpg`, size: 11478935, modtime: 16535504701972076 2022/06/02 09:50:49.512 [D] Walk `F:\\test` end at 2022-06-02 09:50:49.512089 +0800 CST m=+0.077581901 2022/06/02 09:50:49.512 [D] Walk `F:\\test` last for 1.585ms 2022/06/02 09:50:49.512 [D] Total file count cached 2 2022/06/02 09:50:49.516 [D] work flow did start 2022/06/02 09:50:49.518 [D] work consumer 9 start 2022/06/02 09:50:49.518 [D] work consumer 6 start 2022/06/02 09:50:49.518 [D] work consumer 4 start 2022/06/02 09:50:49.518 [D] work consumer 0 start 2022/06/02 09:50:49.518 [D] work consumer 1 start 2022/06/02 09:50:49.518 [D] work consumer 2 start 2022/06/02 09:50:49.518 [D] work consumer 3 start 2022/06/02 09:50:49.518 [D] work producer start 2022/06/02 09:50:49.518 [D] work consumer 7 start 2022/06/02 09:50:49.518 [D] Key:test/path/F:/test/h264_720p.mp4 FileSize:46403015 ModifyTime:16537947588968142 2022/06/02 09:50:49.518 [D] work consumer 5 start 2022/06/02 09:50:49.518 [D] work consumer 8 start 2022/06/02 09:50:49.521 [D] Key:test/path/F:/test/new_start.jpg FileSize:11478935 ModifyTime:16535504701972076 2022/06/02 09:50:49.521 [D] work producer end 2022/06/02 09:50:49.521 [D] work consumer 3 end 2022/06/02 09:50:49.521 [D] work consumer 4 end 2022/06/02 09:50:49.521 [D] work consumer 2 end 2022/06/02 09:50:49.521 [D] work consumer 1 end 2022/06/02 09:50:49.521 [D] work consumer 0 end 2022/06/02 09:50:49.521 [D] work consumer 5 end 2022/06/02 09:50:49.521 [D] work consumer 8 end 2022/06/02 09:50:49.521 [D] work consumer 7 end 2022/06/02 09:50:49.521 [A] Uploading F:\test\F:\test\h264_720p.mp4 [1/2, 50.0%] ... 2022/06/02 09:50:49.521 [A] Uploading F:\test\F:\test\new_start.jpg [2/2, 100.0%] ... 2022/06/02 09:50:49.526 [D] upload: start upload:F:\test\F:\test\h264_720p.mp4 => [timepano:test/path/F:/test/h264_720p.mp4] 2022/06/02 09:50:49.526 [D] upload: start upload:F:\test\F:\test\new_start.jpg => [timepano:test/path/F:/test/new_start.jpg] 2022/06/02 09:50:49.526 [D] resume v1 upload:F:\test\F:\test\h264_720p.mp4 => [timepano:test/path/F:/test/h264_720p.mp4] 2022/06/02 09:50:49.526 [D] resume v1 upload:F:\test\F:\test\new_start.jpg => [timepano:test/path/F:/test/new_start.jpg] 2022/06/02 09:50:49.526 [D] upload: end upload:F:\test\F:\test\h264_720p.mp4 => [timepano:test/path/F:/test/h264_720p.mp4] error:resume v1 upload: open file error:open F:\test\F:\test\h264_720p.mp4: The filename, directory name, or volume label syntax is incorrect. 2022/06/02 09:50:49.526 [E] Upload failed:F:\test\F:\test\h264_720p.mp4 => [timepano:test/path/F:/test/h264_720p.mp4] error:upload error:resume v1 upload: open file error:open F:\test\F:\test\h264_720p.mp4: The filename, directory name, or volume label syntax is incorrect. 2022/06/02 09:50:49.526 [D] upload: end upload:F:\test\F:\test\new_start.jpg => [timepano:test/path/F:/test/new_start.jpg] error:resume v1 upload: open file error:open F:\test\F:\test\new_start.jpg: The filename, directory name, or volume label syntax is incorrect. 2022/06/02 09:50:49.526 [E] Upload Failed, F:\test\h264_720p.mp4 46403015 16537947588968142 error:upload error:resume v1 upload: open file error:open F:\test\F:\test\h264_720p.mp4: The filename, directory name, or volume label syntax is incorrect. 2022/06/02 09:50:49.526 [E] Upload failed:F:\test\F:\test\new_start.jpg => [timepano:test/path/F:/test/new_start.jpg] error:upload error:resume v1 upload: open file error:open F:\test\F:\test\new_start.jpg: The filename, directory name, or volume label syntax is incorrect. 2022/06/02 09:50:49.526 [D] work consumer 9 end 2022/06/02 09:50:49.526 [E] Upload Failed, F:\test\new_start.jpg 11478935 16535504701972076 error:upload error:resume v1 upload: open file error:open F:\test\F:\test\new_start.jpg: The filename, directory name, or volume label syntax is incorrect. 2022/06/02 09:50:49.526 [D] work consumer 6 end 2022/06/02 09:50:49.526 [D] work flow did end 2022/06/02 09:50:49.526 [A] --------------- Upload Result --------------- 2022/06/02 09:50:49.526 [A] Total: 2 2022/06/02 09:50:49.526 [A] Success: 0 2022/06/02 09:50:49.526 [A] Failure: 2 2022/06/02 09:50:49.526 [A] Overwrite: 0 2022/06/02 09:50:49.526 [A] NotOverwrite: 0 2022/06/02 09:50:49.526 [A] Skipped: 0 2022/06/02 09:50:49.526 [A] Duration: 14.7543ms 2022/06/02 09:50:49.526 [A] --------------------------------------------- 2022/06/02 09:50:49.526 [A] See upload log at path:C:\Users\Larry.qshell\users\yuan\qupload\f0258c49fd08de0df8754e41351d3274\log.txt


你的路径是配的是 `F:\\test` ？路径应该配成 `F:\test`

**Comment by mpetrel** [comment]
试了一下，一个斜杠确实可以。因为是windows路径，用了双斜杠，加上之前的版本也可以。。
