### ISSUE TITLE
qshell listbucket2 支持多线程

### ISSUE THREAD

**Issue by CCCCCaO** [qiniu/qshell#341]
#### 需求描述
目前listbucket2只支持单线程的样子，我们存放在KODO的文件量非常大，大约2个亿，当运行
qshell listbucket2 xxxx -o xxxx.txt的时候，发现非常慢，能否进行性能优化？
如果后台运行，将无法返回marker，如果前台运行，则需要人工保证终端不断
请问这块有没有优化计划？比如2亿文件，可以启2个线程，第一个从0-1亿，第二个从1亿到2亿

**Comment by bachue** [comment]
由于设计理念方面的限制，listbucket 无法做到多线程列举文件。
