### ISSUE TITLE
请在 README.md 中添加qshell 更新操作说明

### ISSUE THREAD

**Issue by xiaoliwe** [qiniu/qshell#350]
#### 需求描述
遇到新版本升级的操作，潜意识在 `qshell -h` 中寻找，但没有相关命令.

#### 其他相关建议
-- 在 `README.md` 中添加 "更新操作" 说明; 
-- 在 `qshell commands` 中添加 "update" 操作.

**Comment by YangSen-qn** [comment]
感谢您的反馈，我们后面会对此做优化

**Comment by xiaoliwe** [comment]
官方人员已经回复,期待后续优化调整.
