### ISSUE TITLE
为什么我非要指定一个文件来作为命令的输入？

### ISSUE THREAD

**Issue by capraynor** [qiniu/qshell#378]
#### 需求描述

qshell cdnrefresh

为什么我一定要指定文件？ 我直接写在命令行里面不好吗？

**Comment by YangSen-qn** [comment]
当前也可以不指定文件，当不加 -i 选项时会从 stdin 读取文件链接列表信息，你可以一个一个的输入，每行一个文件链接，输入结束后 Ctrl-D 即可。
