### ISSUE TITLE
file_list 没有用吗

### ISSUE THREAD

**Issue by gebin** [qiniu/qshell#39]
"file_list":"test.min.js",

我设置了file_list但是仍然上传了所有的文件

**Comment by jemygraw** [comment]
不是这样用的，file_list 是用  dir_cache 命令根据目录生成的一个文件列表。

**Comment by gebin** [comment]
那也就说我用dir_cache生成文件列表之后，把不想同步的文件地址删除，然后在file_list指定这个文件，就可以对吧，

**Comment by gebin** [comment]
已经尝试了，可以实现我的要求，=
