### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by geoschen** [qiniu/qshell#396]
#### 问题描述

上传文件失败
QShellError:%s%!(EXTRA *data.CodeError=upload source => form upload: open file: => )
TJ04-1_SAR_STRIP_20230701_230730_S01_I06_001_SNAP_L1A\SLC.data\tie_point_grids\slant_range_time.hdr	289	16906812211897339	QShellError:%s%!(EXTRA *data.CodeError=upload source => form upload: open file: => )

**Comment by YangSen-qn** [comment]
@geoschen 原因是上传的文件无法被 open，确认下文件是否存在
