### ISSUE TITLE
Apple Mac Mini M1芯片编译后无法运行

### ISSUE THREAD

**Issue by makediff** [qiniu/qshell#415]
#### 问题描述
在 Apple Mac Mini M1 芯片上编译得到的可执行文件无法运行，提示
```
./qshell: line 1: syntax error near unexpected token `newline'
./qshell: line 1: `!<arch>'
```

#### 重现步骤
```bash
➜  qshell git:(master) go build -o qshell && chmod +x qshell
➜  qshell git:(master) ✗ ./qshell -h
./qshell: line 1: syntax error near unexpected token `newline'
./qshell: line 1: `!<arch>'
```

#### 期望结果？

- 期望能运行

#### 实际结果？

-

#### 相关环境信息
- **操作系统**：
- **qshell版本**:

**Comment by bachue** [comment]
@makediff 可以测试下 https://github.com/qiniu/qshell/releases/download/v2.14.0/qshell-v2.14.0-darwin-arm64.tar.gz 里的可执行文件，这个文件就是在 Github 上编译出来的。我这边测试没有问题。

**Comment by makediff** [comment]
你好，可以了
谢谢
