### ISSUE TITLE
`qupload`  `check_hash` 设为 false，相同文件是否还会缓存？

### ISSUE THREAD

**Issue by vincentbel** [qiniu/qshell#45]
设置 `qupload`  `check_hash` 为 `false` 后，每次上传，同一文件都会重新上传一遍。对于这种文件，浏览器缓存还有效吗？

**Comment by jemygraw** [comment]
你如果在同一个目录下执行上传的命令，同一个文件是不会重复上传的。

**Comment by vincentbel** [comment]
@jemygraw 我上传文件是在 [Travis CI](https://travis-ci.com) 上上传的，所以每一次都会是新环境，大概过程是：

```sh
git clone ...

# and then building content

qshell upload ...
```
