### ISSUE TITLE
本地删除文件云端无法同步删除

### ISSUE THREAD

**Issue by zema1** [qiniu/qshell#46]
问题如题，我想这应该也是为了安全起见，但能否加一个字段，允许将本地不存在的文件删除。

**Comment by jemygraw** [comment]
不支持删除操作的同步，出于安全考虑。
如果需要删除，可以使用batchdelete功能

**Comment by zema1** [comment]
有强迫症的我自己撸了个脚本，可以变相实现这个功能，需要的童靴们看这[七牛同步删除工具](https://github.com/zema1/qiniu-sync-delete)

这下看着舒服多了。。
