### ISSUE TITLE
七牛API变动造成的编译错误

### ISSUE THREAD

**Issue by micooz** [qiniu/qshell#5]
由于七牛的API有变动，编译时会出现cannot find package，原github.com/qiniu/api已发生改变：
### v7.x
- 请访问： https://github.com/qiniu/api.v7
### v6.x
- 请访问： https://github.com/qiniu/api.v6 (供基于老版本的SDK客户升级用)

qshell应该是基于老版本的api实现，可否考虑更新一下？

**Comment by jemygraw** [comment]
嗯，谢谢，我待会儿改一下。因为我本地有旧的副本。

**Comment by jemygraw** [comment]
@Micooz 已经改好了，你pull一下代码试试。
