### ISSUE TITLE
qshell支持保存在本地的ak，sk的加密读取

### ISSUE THREAD

**Issue by jemygraw** [qiniu/qshell#50]
另外每个依赖ak，sk的命令运行时输出一行提示信息，提示ak，sk加密存储的位置。

**Comment by t1anz0ng** [comment]
完成了加密过程，并且在访问到旧版本保存的account信息时会主动进行加密再进行访问。
另外有依赖于aksk的命令都会输出 account.json的存储地址

**Comment by jemygraw** [comment]
fixed in b13e7a7bd83079e65bda623f099eef45af168011

**Comment by QwertyJack** [comment]
账户信息有加密吗？

**Comment by jemygraw** [comment]
@QwertyJack 保存到本地的内容目前是有加密的。
