### ISSUE TITLE
给qshell的batch功能都加上确认码验证，提醒使用者这些操作很危险。

### ISSUE THREAD

**Issue by jemygraw** [qiniu/qshell#6]
基本做法是：

提示用户要做危险操作了，请输入验证码。验证码用6位随机字符串来避免y/n的误输入。

**Comment by longbai** [comment]
就输入yes no 好了

**Comment by jemygraw** [comment]
效果如此：

jemy@jemy-MacBook ~/QiniuCloud/Projects/qshell/src (master*) $ ./main batchchgm if-pbl if-pbl.txt
<DANGER> Input bdfigb to confirm operation: dasd
Task quit!

**Comment by jemygraw** [comment]
fc0e9824d24c94fa93a3fdb7fb83bef4ed4a8d01

**Comment by longbai** [comment]
建议用相关资源 名字做个确认

**Comment by jemygraw** [comment]
@longbai 相关资源名字是指？

**Comment by longbai** [comment]
比如bucket 名字

**Comment by jemygraw** [comment]
@longbai 有道理。

**Comment by longbai** [comment]
就像github删除repo要让你输入repo名字，这样关联性比较强，而不是认为是独立的任务去完成。
