### ISSUE TITLE
增加一个 --bail 参数，在上传失败的时候返回失败的退出状态

### ISSUE THREAD

**Issue by longtian** [qiniu/qshell#60]
*背景：*
我们在用 qshell 做持续部署，也就是用 Jenkins 在一段 shell 里调用 qshell，整个过程都是自动化的。自动化脚本有一个特点就是依赖于命令的退出状态，一些列命令里有任何一个命令失败了，构建就应该被标注为失败。

*期望：*
如果全部上传成功，返回 0
如果部分文件上传失败，返回 1

*实际：*
即使有的文件上传失败了，qshell 进程的退出状态也是 0 ，这样脚本就不知道上传是否全部成功（除非每次都人肉看一眼 Log，但是这样就违背了自动化的初衷）

*参考：*
可以参考 `s3` 命令行的设计，写的很清楚：
https://docs.aws.amazon.com/cli/latest/topic/return-codes.html

*兼容性：*
为了和现有的脚本兼容，建议增加一个 `--bail` 参数，只有加了这个参数，`qshell` 才会在报错的时候（例如部分上传失败）返回非 0 的退出状态。

**Comment by jemygraw** [comment]
发布2.0.2版本，问题解决

**Comment by jackple** [comment]
@jemygraw 
```bash
2019/05/30 10:42:06 [E] Form upload file `xxx.js` => `xxx.js` failed due to nerror `We encountered an internal error. Please try again`
```
报错还是能继续跑
