### ISSUE TITLE
qupload覆盖上传直接给出上传成功的文件列表

### ISSUE THREAD

**Issue by cnweibo** [qiniu/qshell#62]
是否可以将qupload覆盖上传或者新创文件上传直接生成一个文件列表，这样我们刷新操作时，直接拿这个文件，稍做下修改（加上http://xx.xxx.yy前缀）直接在七牛后台刷新，这样减轻运维工作量

**Comment by jemygraw** [comment]
这个可以做到，我给qupload添加一个参数 overwrite_log 吧

**Comment by cnweibo** [comment]
好的，期待

**Comment by cnweibo** [comment]
再偷懒一下，是否可以在生成这个文件时再加一个参数比如urlprefix, 工具qupload上传后直接给出所有覆盖或者新增文件url列表，而这个文件又可以作为qshell refreshcdn 命令的输入文件，一次性命令全部完成上传和刷新工作，大大解放我们的维护工作量，提高效率

**Comment by jemygraw** [comment]
有个问题，就是cdn刷新每天是有限额的，否则我早就把自动刷新的功能加进去了。

**Comment by cnweibo** [comment]
哦，这个没有关系的，工具只刷新更新过的应该还没有什么问题吧。再说了，工具有这个功能，使用的人也知道有限额，自己掌握控制就好了

**Comment by cnweibo** [comment]
或者还是分两步走，qupload输出待更新文件的列表文件，由用户自己再次运行cdnrefresh命令用上那个列表文件就行了

**Comment by jemygraw** [comment]
在新版2.1.1 里面可以为qupload增加几个选项。比如
```
$qshell qupload -overwrite-list tofresh.txt 10 upload.conf
```
可以参考文档：https://github.com/qiniu/qshell/blob/master/docs/qupload.md#高级用法
