### ISSUE TITLE
qshell cdnrefresh 支持dir目录url吗？

### ISSUE THREAD

**Issue by cnweibo** [qiniu/qshell#63]
请问qshell cdnrefresh http://a.xx.com/static/* 这样支持把/static下面的所有子目录都刷新吗？
试了一下好像不行啊，希望能够支持，这样减轻运维工作量

**Comment by jemygraw** [comment]
七牛的API接口支持刷新 http://a.xxx.com/static/ 这种方式，不过需要开通额外的权限，这个功能目前工具里面没有加，可以加一下

**Comment by cnweibo** [comment]
了解，希望能够尽快加上，我已经把qshell upload作为部署脚本的一部分，就缺自动刷新了

**Comment by jemygraw** [comment]
刷新目录的话，建议还是到后台操作吧，因为次数限制，做了意义不是很大。

**Comment by cnweibo** [comment]
后台操作还是很麻烦的，不自动化容易出错啊。一般发布版本也不太可能每天搞很多版本的。
请考虑做好啊，用不用，怎么用由用户来决定啊
多谢

**Comment by robot-for-adoo** [comment]
@cnweibo   是的自动部署刷新目录比较重要，部署的时候次数不会很频繁，次数限制不是大的问题。@jemygraw

**Comment by jemygraw** [comment]
2.0.5以后支持。
