### ISSUE TITLE
两个关于文档的问题

### ISSUE THREAD

**Issue by aulian** [qiniu/qshell#66]
两个问题都是关于文档的

第一个，我用的是qshell_linux_amd64 v2.0.0版本，
根据该文档（ http://developer.qiniu.com/code/v6/tool/qshell.html#command-option ），设置不交互应使用-f参数，而亲测该程序并不支持-f参数
./qshell_linux_amd64 -m -f batchdelete abc abc.list.txt
提示flag provided but not defined: -f
后来根据程序提示应该写成这样：
./qshell_linux_amd64 -m batchdelete -force abc abc.list.txt
然而在https://github.com/qiniu/qshell/wiki/batchdelete这页中也并未找到相关说明

第二个，该文档提到了多账号的情况，但给出的示例中并未给出-m参数，会造成一定的误导
http://developer.qiniu.com/code/v6/tool/qshell.html#using

妥否

**Comment by aulian** [comment]
好吧 发完了才发现原来github上的文档更新的比较及时 qiniu上的大概是放弃了吧

**Comment by jemygraw** [comment]
嗯，是v2版本之后改变了选项，多谢反馈，我们尽快同步更新。
