### ISSUE TITLE
qupload同步删除问题

### ISSUE THREAD

**Issue by terminatorheart** [qiniu/qshell#74]
在本地文件夹中有文件删除和新增的情况下，qshell_linux_amd64会执行失败，并报错  
[E] Error stat local file `****` due to `stat ****: no such file or directory`  

初次同步目录结构如下：
vender
│   ├── jquery
│   │   ├── jquery1.7.2.min.js
│   │   └── jquery1.9.1.min.js

现在想要同步的目录结构如下
vender
│   ├── jquery
│   │   ├── jquery.js

即删除了原来的两个文件，新增了一个文件

补充：
经过测试，qrsync工具没有这个问题

**Comment by OumCc** [comment]
同问，`qshell_darwin_amd64` 也是类似的情况。

**Comment by t1anz0ng** [comment]
@terminatorheart @NicholasNC 
配置文件有个  `rescan_local` 字段设置为true了吗，没有的话填一下。
