### ISSUE TITLE
？？

### ISSUE THREAD

**Issue by fakership** [qiniu/qshell#75]
我真想知道写个demo能死啊？

**Comment by t1anz0ng** [comment]
文档里都有示例
比如 [listbucket](https://github.com/qiniu/qshell/blob/master/docs/listbucket.md) 最下面
首页目前也加入了一个简单的演示 [demo](https://asciinema.org/a/3l4d74sb2s01lwbt2y3k83p5l)
@fakership

**Comment by jemygraw** [comment]
@faker
