### ISSUE TITLE
请支持http/https代理服务器，特别是windows版

### ISSUE THREAD

**Issue by minichen2000** [qiniu/qshell#81]
请支持http/https代理服务器，特别是windows版！

**Comment by QwertyJack** [comment]
linux下设置环境变量‘https_proxy’&'http_proxy'.
参考：https://stackoverflow.com/questions/10383299/how-do-i-configure-go-to-use-a-proxy

**Comment by xueshanlinghu** [comment]
同，电脑有代理，就用不了了，求弄~

**Comment by jemygraw** [comment]
计划在新工具里面实现。
