### ISSUE TITLE
qshell exit code is 1, after run qshell qupload qiniu.config.js

### ISSUE THREAD

**Issue by iflamed** [qiniu/qshell#82]
See this code: https://github.com/wyvernnot/qshell-cli/blob/master/bin/qshell#L18

qshell version:
> http://devtools.qiniu.com/qshell-v2.0.5.zip

This version will get a error when use npm script.

Alsot see this issue: https://github.com/wyvernnot/qshell-cli/issues/1

**Comment by jemygraw** [comment]
请参考 https://github.com/qiniu/qshell/issues/69 ，一般为网络错误，需要提供日志查看
