### ISSUE TITLE
Using qshell sync cause go error: "panic: runtime error: index out of range"

### ISSUE THREAD

**Issue by CyCle1024** [qiniu/qshell#83]
The resource url is "http://ws.acgvideo.com/1/95/15676778-1.flv?wsTime=1490877996&platform=pc&wsSecret2=1311f8eeb77a279dc97ead59873dc032&oi=2067474736&rate=1350", developer might try to download this url on your own qiniu cloud and see if the qshell report the same error.

**Comment by CyCle1024** [comment]
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x72a760, 0xc4200100e0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
qshell.parseContentRange(0x0, 0x0, 0xd, 0x0)
	/Users/jemy/QiniuCloud/Projects/qshell/src/qshell/sync.go:339 +0x1fd
qshell.rangeMkblkPipe(0x7fff59a84800, 0x8b, 0x0, 0x400000, 0x0, 0xc420113bf0, 0x7fff59a8489c, 0xc, 0x0, 0x0, ...)
	/Users/jemy/QiniuCloud/Projects/qshell/src/qshell/sync.go:237 +0x569
qshell.Sync(0xc4201adca8, 0x7fff59a84800, 0x8b, 0x7fff59a8488c, 0x5, 0x7fff59a84892, 0x9, 0x7fff59a8489c, 0xc, 0x0, ...)
	/Users/jemy/QiniuCloud/Projects/qshell/src/qshell/sync.go:148 +0xbe6
cli.Sync(0x7fff59a847fb, 0x4, 0xc42000a0e0, 0x4, 0x4)
	/Users/jemy/QiniuCloud/Projects/qshell/src/cli/sync.go:44 +0x40e
main.main()
	/Users/jemy/QiniuCloud/Projects/qshell/src/main.go:132 +0x450

**Comment by jemygraw** [comment]
原始链接失效。
