### ISSUE TITLE
Error: get current user error, user: Current not implemented on linux/amd64

### ISSUE THREAD

**Issue by benvirus** [qiniu/qshell#84]
在使用qshell v2.0.5时
qshell account $QINIU_ACCESS_KEY $QINIU_SECRET_KEY
Error: get current user error, user: Current not implemented on linux/amd64

**Comment by t1anz0ng** [comment]
[cross-compiling-user-current-not-implemented-on-linux-amd64](http://stackoverflow.com/questions/20609415/cross-compiling-user-current-not-implemented-on-linux-amd64)

**Comment by jemygraw** [comment]
这个问题，后续不会出现，我们将发布各自系统平台编译的版本。
