### ISSUE TITLE
建议提供latest版本的qshell

### ISSUE THREAD

**Issue by benvirus** [qiniu/qshell#85]
建议提供latest版本的qshell, 这样可以实现自动更新，配合docker使用。

**Comment by jemygraw** [comment]
什么是latest的qshell？

**Comment by benvirus** [comment]
就是一个固定的uri，然后每次都是最新版本的包。而不是像现在一样，每次更新一个版本，下载包的下载地址就变了，然后CI会报错。不过也没关系，可以自己放一个稳定的包到服务器上，用自己的地址。

**Comment by jemygraw** [comment]
嗯，这个问题很好，目前发版本主要是考虑到CDN缓存的问题，所以带上了不同版本。
