### ISSUE TITLE
GitHub  Release Zip 不能被正常解压

### ISSUE THREAD

**Issue by benvirus** [qiniu/qshell#86]
环境: Ubuntu 14.04
在使用从github上下载下来的zip包进行解压时报错：
![image](https://cloud.githubusercontent.com/assets/13535932/24505412/69b2660c-158c-11e7-9ad9-ba52371a58f6.png)
和版本无关，因为从2.02到2.04我都试过了。

**Comment by jemygraw** [comment]
这个是github打包的zip吧

**Comment by benvirus** [comment]
请提供可以解压的压缩包啊。官方提供的2.05压缩包可以解压，但是执行会有问题。
