### ISSUE TITLE
七牛越做越大，东西越来越难用

### ISSUE THREAD

**Issue by ghost** [qiniu/qshell#93]
以前下载下来就可以用，现在各种报错，都没人维护吗？也没人管了吗？
![image](https://cloud.githubusercontent.com/assets/3073370/26087939/875f1a74-3a26-11e7-800b-177fa43d8f7a.png)

**Comment by jemygraw** [comment]
这个根本原因是你的配置文件不正确，没有按照文档要求去写。看错误就是配置文件解析失败啊。
