### ISSUE TITLE
如何只下载一个文件，如copyToLocal的功能呢，只能使用qdownload么？

### ISSUE THREAD

**Issue by zhouqing86** [qiniu/qshell#94]

**Comment by zhouqing86** [comment]
如果连下载文件的功能都木有的话，简直醉了

**Comment by jemygraw** [comment]
wget, curl 都可以下载一个文件嘛。

**Comment by zhouqing86** [comment]
@jemygraw 谢谢回复！我的需求是将项目构建的不同版本zip包放到七牛私有库上，而后使用ansible 根据版本信息做部署。
私有库是需要生成token才能访问的，curl与wget用起来绕了一圈。
最后使用的方式是用`qshell qdownload 1 qshell_download.json`

```
{
  "dest_dir"   :   "/tmp",
  "bucket"     :   "xxx-bucket",
  "prefix"     :   "xxxapp-{{ build_version }}",
  "suffixes"   :   ".gz"
}
```

不过还是建议qshell能够很方便的download某个文件。

**Comment by jemygraw** [comment]
嗯，qdownload很适合批量下载文件，可以当作batch get来用吧。
