### ISSUE TITLE
listbucket有必要指定输出文件吗？

### ISSUE THREAD

**Issue by QwertyJack** [qiniu/qshell#96]
建议：
```
... [-o output_file]
缺省：输出到标准输出
```

另外我更喜欢`ls`这个命令而不是`listbucket`

**Comment by jemygraw** [comment]
可以使用
```
$ qshell listbucket bucketname prefix stdout
```
把输出文件名指定为stdout就可以输出到终端。

**Comment by QwertyJack** [comment]
还有其他哪个命令会向你这么奇葩用'stdout'代表标准输出？

**Comment by jemygraw** [comment]
@QwertyJack 对于listbucket来说，大多数的情况下，都是需要指定一个输出文件的，因为输出太多了直接输出到终端没法看，但是有些情况下，你测试程序的时候获取空间文件很少，想list出来看看，那么用`stdout`作为输出文件名就可以输出到终端。`stdout`本身就表示标准输出嘛，当然可以用了。其他工具没有，我的算创新嘛。

**Comment by QwertyJack** [comment]
通常用‘-’代表stdout

**Comment by jemygraw** [comment]
@QwertyJack 如果有人看不懂`-`，又会跑来骂我。
