### ISSUE TITLE
可选参数有歧义

### ISSUE THREAD

**Issue by QwertyJack** [qiniu/qshell#97]
你开心就好

**Comment by jemygraw** [comment]
你说的是哪个命令？那个rput和fput没有歧义，顺序无所谓，会根据你指定的内容来判断是什么参数。

**Comment by QwertyJack** [comment]
真nb

**Comment by jemygraw** [comment]
@QwertyJack 哈哈，这个工具我用的次数比大多数人都多，怎么方便，我怎么设计的。
